### ISSUE TITLE
[Progress Bar] High volume of warnings from adding shorthand margin styles

### ISSUE THREAD

**Issue by yogurtandjam** [uber-web/baseui#1011]
https://codesandbox.io/s/8x8n4po2ql

Currently the styling on the progress bar uses 4 longhand margin styles to create a 12px margin uniformly.
Using shorthand margins causes an extremely high volume of warnings, interfering significantly with console visibility.

Very willing to submit a PR to detect shorthand margins and cascade into longhand styles to prevent this
```
Overriding progressbar style 
margin: 0, padding: 0 yields warnings:
Styles `{"margin":0}` and `{"marginBottom":"12px"}` in object yielding class
"af ag ah ai aj ak al am" may result in unexpected behavior.
Mixing shorthand and longhand properties within the same style object is
unsupported with atomic rendering.
https://codesandbox.io/s/8x8n4po2ql
```

**Comment by chasestarr** [comment]
I recommend always using longhand properties. Refer to the styletron docs for a better description: https://www.styletron.org/concepts/#shorthand-and-longhand-properties

There may be some expansion you could do outside of base ui to save key strokes, but is likely not something we would like to build in the core package
