### ISSUE TITLE
Select in Modal draws under Modal

### ISSUE THREAD

**Issue by parkerdan** [uber-web/baseui#1022]
Upgrading from `6.2` to `6.6` and it breaks some of our UI.

We render a `Select` in a `Modal` and the `Select` dropdown contents are drawn under the `Modal` and therefore unselectable

**Comment by gergelyke** [comment]
Hi Dan! in our next sprint (starting next Monday) we'll add a z-index manager to Base Web, as we've run into issues like this in the past. For the time being, we'd like to ask you to work around it using the overrides pattern, and pass in a zindex https://baseweb.design/theming/understanding-overrides/

**Comment by tajo** [comment]
Just a note: You should override the Modal `zIndex` in this case.

**Comment by parkerdan** [comment]
> Hi Dan! in our next sprint (starting next Monday) we'll add a z-index manager to Base Web, as we've run into issues like this in the past. For the time being, we'd like to ask you to work around it using the overrides pattern, and pass in a zindex https://baseweb.design/theming/understanding-overrides/

I understand I can correct things with overrides.  I am just reporting the issue as the default behavior should not be like this IMO.

**Comment by gergelyke** [comment]
Yes, we agree - we'll land a fix next week

**Comment by parkerdan** [comment]
> Yes, we agree - we'll land a fix next week

We will just stay on `6.2` until upgrades are smooth.

We love baseui!!  Keep up the good work!!

**Comment by yctercero** [comment]
Hi there!

I am running into a similar problem with the PhoneInput country dropdown. We are using it within a modal of ours (we are not using the BaseUi modal component). When a user selects the country, the dropdown renders behind our modal. I attempted to use the overrides by targeting 'CountrySelectDropdown', but it is not doing anything. 

When I inspect, I see that the component that I need to target is the popover component being used within PhoneInput, but haven't found a way to do so.

Would appreciate any suggestions, thanks!

**Comment by yctercero** [comment]
Hi there!

I am running into a similar problem with the PhoneInput country dropdown. We are using it within a modal of ours (we are not using the BaseUi modal component). When a user selects the country, the dropdown renders behind our modal. I attempted to use the overrides by targeting 'CountrySelectDropdown', but it is not doing anything.

When I inspect, I see that the component that I need to target is the popover component being used within PhoneInput, but haven't found a way to do so.

Would appreciate any suggestions, thanks!

**Comment by tajo** [comment]
@yctercero Are you using the latest `baseui` version? It should work correctly out of the box unless you are setting `zIndex` somewhere. More info: https://baseweb.design/components/layer/

**Comment by yctercero** [comment]
Thanks for the link @tajo! We had misplaced the BaseProvider.
