### ISSUE TITLE
[error] deploying hello world with next and now

### ISSUE THREAD

**Issue by YobertyAlej** [uber-web/baseui#1033]
Error thrown at hello world example deployment using next.js and now

baseui + next.js configuration from: https://www.styletron.org/getting-started/#with-nextjs
Hello World example from official usage: https://github.com/uber-web/baseui#usage

## Current Behavior

_After running now, console logs an error_

**baseui@6.6.0** throws an error at :

**error baseui@6.6.0**: The engine "node" is incompatible with this module. Expected version ">=8.11.0". Got "8.10.0

## Expected Behavior

The simple hello world example usage to be build successfully, deployed and running live on now

## Your Environment

| Tech    | Version |
| ----------- | --------- |
| Base UI | v6.6.0  
| React    | 16.8.4  
| Next      | 8.0.3
| Now      | 14.1.0 
| Chrome |  Version 71.0.3578.80 (Official Build) (64-bit)
| Ubuntu  | 18.04.1 LTS
| VSC      | 1.32.1

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
Hi @YobertyAlej ! can you please update your Node.js version to be at least 8.11.0, as the error message suggests?

**Comment by efleurine** [comment]
hi @gergelyke out of your mind does downgrading to 8.10 would case a significant issue. 
the thing is now platform only use the 8.10 currently.

thanks.
