### ISSUE TITLE
[RFC] bundling + tooling

### ISSUE THREAD

**Issue by rtsao** [uber-web/baseui#104]
- [x] Drop Rollup and just use Babel for transpilation, no need to bundle the library
- [ ] Use file extensions in imports statements, so it is valid ESM and module resolution would work without bundling in the browser (i.e. someone could use unpkg.com urls and `<script type="module">` instead of webpack). You can change the import lint rule to enforce this
- [x] Use webpack to bundle E2E tests

**Comment by gergelyke** [comment]
@rtsao can you help how I should change the import rule lint to enforce this?

**Comment by rtsao** [comment]
IIRC there’s a way to enforce that relative imports have file extensions.

I think I tried this out but it didn’t support auto-fixing, so we’ll probably want to codemod the changes.

**Comment by chasestarr** [comment]
is enforcing file extensions still a priority? this eslint [rule](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md) seems to do what we want. i could take care of the codemod fairly quick

**Comment by gergelyke** [comment]
That would be great @chasestarr !
