### ISSUE TITLE
[File-uploader] Allow to override button component

### ISSUE THREAD

**Issue by AndrewUldin** [uber-web/baseui#1045]
## Feature description
That would be great to have an opportunity to override button component. I have a request from UI-designer to implement file-uploader as only a button without drag-and-drop area. I easily changed styles for drag-and-drop but button is fixed and also overrides base button.

**Comment by IgorWilbert** [comment]
Hello @AndrewUldin ! Is there anyone working on this issue? If not, may I take it? Thanks!
