### ISSUE TITLE
[Toast] Consider adding a wrapper and moving the icon inside

### ISSUE THREAD

**Issue by jasonbarone** [uber-web/baseui#1079]
## Feature description
The Toast component has an optional close icon, which is rendered as a direct child of the `Body` wrapping component. props.children is a sibling. This makes more difficult to style the icon for full-width notification styles that have a max-width on the inner content. In other words, if your props.children components has a max-width with auto margins, your icon will be outside of the container and will just float all the way to the body container.

It would be great to have a style-able inner body component, in which the icon is rendered.

**Comment by chasestarr** [comment]
@jasonbarone do you mind sharing a codesandbox reproducing the issue? Here's something to get started: https://codesandbox.io/s/8x8rzm0j68?module=/example.js

**Comment by chasestarr** [comment]
I would rather not add an additional wrapper + override, when this use-case is currently possible check out https://codesandbox.io/s/62o4k86p23
