### ISSUE TITLE
Proposal: Remove e2e/e2e.js in favor of usinga docker-compose workflow

### ISSUE THREAD

**Issue by KevinGrandon** [uber-web/baseui#108]
The current script at `e2e/e2e.js` composes multiple build steps and service orchestration, which can be defined clearly in a standardized file format within docker-compose.

In https://github.com/uber-web/baseui/pull/95 we are adding support for spinning up necessary services (a chrome selenium service, as well as the webserver). We should be able to leverage the same docker based workflow locally, as well as in CI.

**Comment by gergelyke** [comment]
fixed in https://github.com/uber-web/baseui/commit/f7b07772b0166118a4313d4ea38ec536e7444d18
