### ISSUE TITLE
[Avatar] Enable top-level API to render initials by default

### ISSUE THREAD

**Issue by chasestarr** [uber-web/baseui#1085]
Right now, the `Avatar` component assumes that an image will always try to be rendered. Some applications do not provide profile image features to users, but want to show the error fallback state by default. Doing so requires a 'hack' where a developer provides an invalid `src` prop to always trigger the fallback state. 

Here is a reproducing code-sandbox: https://codesandbox.io/s/20203jxn80

There should be a prop to define if it should render initials by default, and ignore the `src` prop

**Comment by tajo** [comment]
Should we just make the `src` prop optional and when missing using the fallback state immediately?

**Comment by chasestarr** [comment]
yeah I think that's a better api 👍

**Comment by ashish-kale** [comment]
Is anyone working on this? Can I pick this up?

**Comment by chasestarr** [comment]
Hi @ashish-kale it is available. Thanks for looking into it. Let me know if you have any questions about developing on the project
