### ISSUE TITLE
Support for Windows set up

### ISSUE THREAD

**Issue by IgorWilbert** [uber-web/baseui#1111]
Hello! I am having many troubles while trying to set up `baseui` on Windows 10. Here are the steps I took:

- The first issue I had was with a `cp command not found` here.https://github.com/uber-web/baseui/blob/cedaaab62c5e137c22e5ee31bb6e559391a230ab/package.json#L26
 After changing the command to `copy` and updating the paths with backslash instead of slash, the file was copied. 
- After that I had troubles with lines that execute Javascript files, like this one.  https://github.com/uber-web/baseui/blob/cedaaab62c5e137c22e5ee31bb6e559391a230ab/package.json#L27 I solved it by appending `node` in the front, like this: `"build:copy-flow-files": "node .\\scripts\\flow-copy-src.js"`

- At this point, I was able to run the `yarn` command with no errors. When I try to run `yarn documentation:dev`, after some time it shows the message `babel compiled 314 files successfully`. However the console does not run any process at all after this, neither gives you the option to enter other commands nor launches the documentation on `localhost`, as it should. If I try to run `yarn documentation:serve` instead, I get a `404 not found` error. 

I don't think making so many changes on `package.json` and other files is a reasonable solution. I am considering installing `Linux OS`system and `Windows Subsystem for Linux` on my machine but I REALLY wanted to avoid doing this. I already set up the project on a macbook successfully, so it is definitely a problem with Windows. Any help is welcome. Thanks!

P.S. I'll provide more details about my set up when I get home.

**Comment by gergelyke** [comment]
Thanks for opening this issue @IgorWilbert - I can put up a PR quickly to fix this

**Comment by IgorWilbert** [comment]
@gergelyke sorry, do you want me to fix it or will you fix it?

**Comment by gergelyke** [comment]
If you can, that's great! But I am happy to do that too - let me know what you prefer

**Comment by IgorWilbert** [comment]
I would really appreciate if you could do it, since I claimed other 2 issues already. Thanks a lot!!!

**Comment by gergelyke** [comment]
can you give this a try ? https://github.com/uber-web/baseui/pull/1112

**Comment by IgorWilbert** [comment]
@gergelyke sorry, I can only give a try when I get home in around 5 hours, but I'll let you know about it. Thanks!

**Comment by gergelyke** [comment]
sounds good, thank you! please reopen if needed! :)

**Comment by IgorWilbert** [comment]
Hi @gergelyke ! Unfortunately, I am still having some trouble. `yarn` command was run without errors, but this was the result of `yarn documentation:dev`. The server for the documentation did not launch automatically. I checked `localhost:3000` and `localhost:8081`, but there was nothing to be seen.
![dev](https://user-images.githubusercontent.com/42987854/55523055-ed9dcd80-565d-11e9-9d81-7177e467f7f7.JPG)
When trying to run 'yarn documentation:serve', this was the result
![serve](https://user-images.githubusercontent.com/42987854/55523179-55ecaf00-565e-11e9-9499-2f438e96a1ee.JPG)
On `localhost:8081` there is just a blank page
![serve2](https://user-images.githubusercontent.com/42987854/55523205-6f8df680-565e-11e9-9e9c-1a5e52e79664.JPG)
Setup:
- Windows 10 2018
- node version 8.12.0
- yarn version 1.13.0
Let me know if there is anything else I should have installed on my PC or a command I should have ran but forgot to. Thanks!
P.S. It might take a few hours for me to be able to reply.

**Comment by IgorWilbert** [comment]
Also, I don't have permission to reopen the issue.

**Comment by gergelyke** [comment]
this happens if the dev server cannot start listening on port 3000 - can you double check if you have nothing listening on that port?

**Comment by IgorWilbert** [comment]
I confirm, all ports are available

**Comment by gergelyke** [comment]
@IgorWilbert can you give this branch a try? https://github.com/uber-web/baseui/pull/1121

**Comment by IgorWilbert** [comment]
@gergelyke thanks, I will try it as soon as I get home, I'll let you know how it goes.

**Comment by IgorWilbert** [comment]
Awesome @gergelyke ! On this branch it launched the documentation website on `localhost:3000` with no issues at all! Thank you for such quick fix! But, as it was mentioned on #1121, I think it will be necessary to add `shx` on the other commands.

**Comment by gergelyke** [comment]
should be fixed - let us know if you run into further issues!
