### ISSUE TITLE
Allow adding a prefix to the href attribute of the side-nav

### ISSUE THREAD

**Issue by chirgjn** [uber-web/baseui#1139]
Currently the Link's href is set to item.itemId in the side-nav component. This makes it cumbersome if all Links need to be prefixed.

I can take this up if needed.

**Comment by chasestarr** [comment]
Can the prefix not be applied in the `item.itemId`? I agree this is more effort than a built-in utility in the component, but it allows for a simple interface that all developers understand

**Comment by chirgjn** [comment]
I handled it using a HOC just thought would be a nice addition.

**Comment by chirgjn** [comment]
Hey can I pick this up?

**Comment by chasestarr** [comment]
yes. rather than only a prefix, can it be a transform function?

**Comment by chirgjn** [comment]
Sure, have any good `prop` names in mind for the transformer, `pathTransfromer`?

**Comment by chasestarr** [comment]
`transformItem` ? I would to enable the entire item to be transformed rather than just the item `title`

**Comment by chirgjn** [comment]
:+1: That's a good one, I will start working on the PR then :smile:
