### ISSUE TITLE
[Table] header cell border does not fill vertical space if multiple lines

### ISSUE THREAD

**Issue by chasestarr** [uber-web/baseui#1144]
## Current Behavior

![Image Pasted at 2019-4-12 11-06](https://user-images.githubusercontent.com/5317799/56062744-4a664b80-5d22-11e9-8768-f4dd2593e54e.png)

![image](https://user-images.githubusercontent.com/1380581/56069876-e485be00-5d39-11e9-9a99-af67342ee915.png)

## Expected Behavior

vertical line extends fully

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.13.0  |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by jh3y** [comment]
Can't replicate this 🎉 - https://codesandbox.io/s/table-basic-usage-8hkj4

**Comment by chasestarr** [comment]
cc @ardok - I believe you reported this?
