### ISSUE TITLE
Add Badge component

### ISSUE THREAD

**Issue by IgorWilbert** [uber-web/baseui#1153]
## Feature description
This might be a quite small addition, but I guess it would be nice to add a Badge component, since [Material](https://material-ui.com/demos/badges/) and [Bootstrap](https://react-bootstrap.github.io/components/badge/) have some nice examples of it. Personally, I prefer the Material implementation, since it is significantly different from tag component of baseui.

**Comment by chasestarr** [comment]
Thanks @IgorWilbert - badges are not an established pattern in the design system, so I don't imagine this happening any time soon. Will revisit if designers need something like this

**Comment by IgorWilbert** [comment]
No problem @chasestarr ! I'm still trying to figure out what may or may not be interesting for this project. Feel free to close this issue if it is not relevant at the moment. Thanks!

**Comment by lucasterra** [comment]
@IgorWilbert There is now a `Tag` component, which should serve the purpose of a `Badge` component.
https://baseweb.design/components/tag/
