### ISSUE TITLE
[Slider] Handle labels overlap if too close together

### ISSUE THREAD

**Issue by chasestarr** [uber-web/baseui#1159]
## Current Behavior

![Image Pasted at 2019-4-15 17-15](https://user-images.githubusercontent.com/5317799/56168351-c7e2c380-5f8f-11e9-8a85-153bde4c8abc.png)

## Expected Behavior

I would expect that the labels change position to avoid overlapping

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.13.0  |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by jh3y** [comment]
@tajo Would this be better addressed in the `react-range` package? There could be an internal state for overlap used in the render? Then hide one of the `Thumb` and set the others value to `Thumb 1 Value - Thumb 2 Value` or `Thumb 1 Value` if the values match. Could potentially hook this into the `getOffsets` method as the bounding rect for `Thumb`s are already being grabbed here.

**Comment by tajo** [comment]
@jh3y definitely, there is already a PR and discussion on this issue

https://github.com/tajo/react-range/pull/3

Do you want to take over the PR and push it through? There are some things to consider - we can keep discussion there.

**Comment by jh3y** [comment]
@chasestarr @tajo I have a PR open on `react-range` that will support this 👍 

[tajo/react-range#14](https://github.com/tajo/react-range/pull/14)

Awaiting a little help in getting the `e2e` tests to pass on `ci`. They pass locally in `Chromium`.
