### ISSUE TITLE
[ProgressSteps] Tail overlaps the icon

### ISSUE THREAD

**Issue by leyanlo** [uber-web/baseui#1167]
If you look closely, you’ll see that the ProgressSteps tail overlaps the current step’s icon.

<img width="129" alt="Screen Shot 2019-04-17 at 2 49 12 PM" src="https://user-images.githubusercontent.com/1285326/56324569-13c67180-6124-11e9-878a-ee64a312504b.png">

## Expected Behavior

Would expect the tail to be under the icon, or to at least have no overlap.

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by yogurtandjam** [comment]
https://github.com/uber-web/baseui/pull/1177

**Comment by gergelyke** [comment]
fixed in https://github.com/uber-web/baseui/commit/8fd990f68dadb2993062cec8fa7672e480706ee0
