### ISSUE TITLE
Select Component's Menu Still Catches Click Even When It's No Longer Visible

### ISSUE THREAD

**Issue by healy-uber** [uber-web/baseui#1179]
[Base UI's Select Component](https://baseui.netlify.com/components/select/) has a dropdown menu which conditionally renders depending on if the select component is active. However, after selecting an item, the list persists in the DOM for around 1 second, and can still collect mouse clicks. 

This is an issue for our team at Uber because our Form UI has several `Input` and `Select` components stacked on top of each other and our users realized that sometimes clicking too quickly is selecting the wrong menu item choices.

## Current Behavior
I've made a video that shows the clicks happening so it's easy to visualize the issue:
![Base UI Select List Artifact](https://user-images.githubusercontent.com/44385566/56544788-558f5780-652a-11e9-8809-16d8ae458117.gif)

## Expected Behavior
I would expect that if I were to click again shortly after making a selection that this would not be registered as a menu click and modify my selection.

## Your Environment
| Tech    | Version |
| ------- | ------- |
| Base UI | v6.11.0 |
| React   | v16.4.1 |
| browser | Chrome |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by tajo** [comment]
Looking into it this week. Thanks for the report!

**Comment by tajo** [comment]
Fixed and released as `v6.15.1`

**Comment by healy-uber** [comment]
Thanks @tajo !
