### ISSUE TITLE
[Select] Typing a value that doesn't match any option then clicking elsewhere results in a brief display of the options list

### ISSUE THREAD

**Issue by austintang** [uber-web/baseui#1190]
Here is a GIF of the bug in action:
![select_component_issue](https://user-images.githubusercontent.com/42187119/56773191-076c9500-6772-11e9-86e2-8b0d3ae2fdd3.gif)

## Current Behavior

After typing a value that doesn't match any option, if the user proceeds to click elsewhere, the options list gets displayed for a split second with a horizontal offset.

## Expected Behavior

After typing a value that doesn't match any option, when the user clicks elsewhere, the select value should clear (as it currently does), and the select options list should not be displayed at all.

## Your Environment

I am reproducing this on Base UI's official documentation page on OSX with Chrome version 73.0.3683.103: https://baseweb.design/components/select/

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.15.0  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by tajo** [comment]
Thanks! Looking into this soon.
