### ISSUE TITLE
Toggle Component

### ISSUE THREAD

**Issue by pkrawc** [uber-web/baseui#1205]
## Feature description

There doesn't seem to be a Toggle component and it's a pretty common UI element in a lot of forms.

It's used often to indicate immediate state changes (eg. the interface would use a toggle to allow the user to turn on/off their wifi functionality).

The key properties of a toggle is that is instantly attempts to save the state change and persist it. In this way it's also useful for a toggle to have a loading state if the data change could possibly fail.

## Example UI

![image](https://user-images.githubusercontent.com/7158581/56995077-55184180-6b66-11e9-890e-f71a0f22534e.png)

**Comment by gergelyke** [comment]
hi @pkrawc ! you can find it here: https://baseweb.design/components/checkbox/#checkbox-as-a-toggle

**Comment by pkrawc** [comment]
Thanks for the clarification @gergelyke
