### ISSUE TITLE
Export flow types for Style, Component overrides (and differentiate function vs object)

### ISSUE THREAD

**Issue by vlad** [uber-web/baseui#1209]
## Request: export flow types for overrides to encourage components to follow the base web overrides syntax

As a developer, I would like to enable the same Base Web overrides= interface in my own custom components.  This way, there is one convention in our particular codebase instead of many conventions (such as accepting attributes like component1Style=, componentAbcStyle= ...).

I'm using flow annotations to be specific about the possible overrides= (which subcomponents, and which types of overrides like style:, component:, etc).

This way, I can keep the validations light-weight and easy to understand, and if we ever migrate to another framework in the future (Base Web Rewrite), at least all of our custom components will follow one familiar convention.  And we can easily add or delete other types of overrides by updating the flow type for overrides for that individual component, and a bit of logic in the component itself to handle it.

Example of a custom component with 1 subcomponent and only 'style' override:

```
type ComponentProps = {|
   ...
   overrides?: {Subcomponent: {style: StyleOverrideT}}, // one component, style-only overrides that follow base Web syntax.
|};

function Component({
   ...
   overrides: {},
}: ComponentProps) {
  const subcomponentStyles = _get(overrides, 'Subcomponent.style', {});
  return (<Example style={subcomponentStyles} />);
}
```

1) I'd like to be able to import the flow types for overrides.style and overrides.component from baseui package.  Even if StyleOverrideT is just () => {}, it will be very useful to import the consistent name across our codebase.

2) My flow types are very declarative about what my custom component can support.  In my case, I want to be clear I'm not supporting the functional version of style override.

Therefore, the type should be different for each style: interface.  So maybe the public type exports could be StyleObjectOverrideT, StyleFunctionOverrideT, and StyleOverrideT (for both).

Please let me know what you think!

**Comment by IgorWilbert** [comment]
@chasestarr the need for overriding subcomponents reminds me of #994. Do you any suggestion to implement it in a general way?

**Comment by vlad** [comment]
Thanks @gergelyke.  I updated the description to also ask if we could split StyleOverrideT into multiple types so I could be specific about what kind of override syntax my custom component understands.  Fo example, StyleObjectOverrideT, StyleFunctionOverrideT, and StyleOverrideT (for both).

**Comment by jh3y** [comment]
Hey @vlad 👋 
I've raised [#1438}(https://github.com/uber-web/baseui/pull/1438) exporting two new types which make up the union type for `StyleOverrideT`. Is this what you were looking for?
