### ISSUE TITLE
Add destructive/danger KIND for the Button Component

### ISSUE THREAD

**Issue by chirgjn** [uber-web/baseui#1215]
## Add destructive/danger `KIND` for the `Button` Component
All the currently supported styles `primary`, `secondary`, `tertiary`, and `minimal` don't work for a destructive action like "Delete".

**Comment by chasestarr** [comment]
Hi @chirgjn, this is intentional from design. [This article](https://medium.com/refactoring-ui/7-practical-tips-for-cheating-at-design-40c736799886) (near the bottom) does a good job of describing alternatives.

Going to close for now, but feel free to continue the discussion

**Comment by chirgjn** [comment]
I've read that book :p
My usecase is exactly that: A primary irrevocable destructive action.
The destructive state needs to be used sparsely but it has its place.
Just a small nit, I used overrides with $theme values but it was a lot of work choosing colors for every state (focused, selected etc).

**Comment by chasestarr** [comment]
This is a pattern I recommend if you need alternate button colors: https://github.com/chasestarr/baseweb-workshop/blob/master/src/lessons/customizing-themes/solution.js

**Comment by chirgjn** [comment]
This is going to be so helpful, thanks a lot :)
