### ISSUE TITLE
bug(side-nav) : DarkTheme is not applied as expected

### ISSUE THREAD

**Issue by chirgjn** [uber-web/baseui#1221]
`DarkTheme` doesn't change side-nav's appearance

## Current Behavior
Wrapping `Navigation` inside a `ThemeProvider` and using the `DarkTheme` doesn't change the side-nav appearance as per the docs
https://codesandbox.io/embed/zrp78r8533

## Expected Behavior
It should change the side-nav appearance as per the docs

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.16.0 |
| React   | v16.8.6 |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by IgorWilbert** [comment]
Thanks @chirgjn ! However, `DarkTheme` does change the side-nav appearance, as can be seen here https://codesandbox.io/s/718287n9vq . Did you expect a different change?

**Comment by chirgjn** [comment]
<img width="721" alt="Screenshot 2019-05-02 at 7 40 48 PM" src="https://user-images.githubusercontent.com/3641378/57081408-3fe01600-6d12-11e9-85e7-3159a95ecfdc.png">
 [This](https://baseweb.design/components/sidenav/) is how it shows in the docs with dark theme enabled.

**Comment by gergelyke** [comment]
Hi @chirgjn @IgorWilbert,

we are waiting for design to finalize the side navigation - once that's done, we'll update the component. Thank you for your patience!

In the meantime, you can do something like this, that we did for the documentation site: https://github.com/uber-web/baseui/blob/4dff84a366a4cfe501bb4d852dea4f599258f897/documentation-site/components/sidebar.js#L22-L35

I hope it helps!
