### ISSUE TITLE
[ButtonGroup] Button Group checkbox mode with strange highlight

### ISSUE THREAD

**Issue by IgorWilbert** [uber-web/baseui#1222]
## Current Behavior
![Gif](https://user-images.githubusercontent.com/42987854/57051227-ecf55880-6c56-11e9-8917-ed06e39e921a.gif)

The default being light grey, on hover the button gets dark grey and on click it gets blue, as expected. However, when it is clicked while active (blue), it gets permanently dark grey, and only returns to light grey upon clicking again elsewhere.

## Expected Behavior
 When clicking on the button while active (blue), it should become light grey immediately.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.15.1  |
| React   | ^16.8.3 |
| browser |  Firefox 66.0.3 64-bits  |

- [X] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by IgorWilbert** [comment]
If this happens to be a valid issue, I would like to work on it. Thanks!

**Comment by gergelyke** [comment]
Hi @IgorWilbert ! thanks for opening this issue!

The current behaviour is as expected - the dark grey color stays to show the user what's the focused element, because of accessibility reasons.
