### ISSUE TITLE
feat(header-navigation): Can we implement a stateful version similar to the side-nav

### ISSUE THREAD

**Issue by chirgjn** [uber-web/baseui#1224]
The Side Navigation has stateful version which really comes in handy and covers a large amount of major use-cases, but header navigation lacks a stateful version. It would really help having a stateful version for header navigation.

**Comment by chirgjn** [comment]
I can start working on this, if anyone could confirm that we want to support this :)

**Comment by gergelyke** [comment]
@nadiia @chasestarr @tajo what do you all think?

**Comment by chasestarr** [comment]
sgtm 👍

**Comment by tajo** [comment]
> I can start working on this, if anyone could confirm that we want to support this :)

Yes, we would be happy for a PR!

**Comment by chirgjn** [comment]
I'll start working on it then 😁

**Comment by chirgjn** [comment]
@jh3y thanks for assigning this to me.
I will raise a PR by Monday :D
