### ISSUE TITLE
Grid system

### ISSUE THREAD

**Issue by devey** [uber-web/baseui#1237]
Hallo, do you have any plans to have a [grid system](https://ant.design/components/grid/)?

**Comment by tajo** [comment]
Yes, it's on our radar but not sure when. In meantime, you can use the `<Block />` component that supports all CSS grid and flex properties.

**Comment by parigi-n** [comment]
Nice, it would be really cool to have a bootstrap-like grid system (or whatever easy to use system) integrated directly in BaseUi :+1:
