### ISSUE TITLE
Setting `expanded` on StatefulPanel from Accordion doesn't render it as expanded. 

### ISSUE THREAD

**Issue by lxe** [uber-web/baseui#1259]
https://codesandbox.io/s/k2jnn4vo93

![image](https://user-images.githubusercontent.com/1486609/57414162-dba6d180-71ab-11e9-9483-61bb1e839f2d.png)

## Current Behavior

Setting `expanded` on StatefulPanel from Accordion doesn't render it as expanded. 

## Expected Behavior

Should render as expanded.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.17.2  |
| React   |    16.8.6     |
| browser |    16.8.6     |

- [ X] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by lxe** [comment]
`initialState={{expanded: true}}` works but that doesn't match the docs

**Comment by IgorWilbert** [comment]
Thanks @lxe ! I'll look into it :)

**Comment by nadiia** [comment]
Got a fix for it #1263

**Comment by IgorWilbert** [comment]
Thanks @nadiia ! I think I'll have to be a little faster to keep up with you 😅
