### ISSUE TITLE
noResultsMsg doesn't affect the no results message in Select

### ISSUE THREAD

**Issue by lxe** [uber-web/baseui#1268]
https://codesandbox.io/s/qx0qzjvjpw

<img width="1358" alt="Screen Shot 2019-05-09 at 12 56 13 PM" src="https://user-images.githubusercontent.com/1486609/57482628-f6d01a80-7259-11e9-818e-b9e40ed749cd.png">

noResultsMsg doesn't affect the no results message in Select

<!--

**Comment by tajo** [comment]
Being fixed now. Thanks!

**Comment by tajo** [comment]
Should be fixed in the latest release.
