### ISSUE TITLE
question on code splitting

### ISSUE THREAD

**Issue by shavo007** [uber-web/baseui#1270]
In my boilerplate project I have a dynamic import for Toastr component.

When I look at the webapck bundle analyser, vendors_Toastify it pulls in alot of files related to icon. Is this expected? 

## Your Environment

My repo can be found at https://github.com/shavo007/react-boilerplate

run yarn build to see the report

i have attached a screenshot also

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.17.2  |
| React   |  16.8.6       |
| browser |   chrome      |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by shavo007** [comment]
<img width="430" alt="Screenshot 2019-05-10 at 14 58 40" src="https://user-images.githubusercontent.com/5466825/57503619-3834f880-7334-11e9-9075-072bf13913dc.png">

**Comment by gergelyke** [comment]
fixed in https://github.com/uber-web/baseui/pull/1271

**Comment by gergelyke** [comment]
thanks for reporting @shavo007 !

**Comment by shavo007** [comment]
my pleasure @gergelyke . btw, followed you on risingstack, keep up the good work!

**Comment by gergelyke** [comment]
🤗

**Comment by shavo007** [comment]
![Screenshot 2019-05-21 at 17 05 30](https://user-images.githubusercontent.com/5466825/58075325-c76ec580-7bea-11e9-85c4-0fe3effcd33e.png)

**Comment by shavo007** [comment]
all good
