### ISSUE TITLE
New showcase example on CodeSandbox

### ISSUE THREAD

**Issue by IgorWilbert** [uber-web/baseui#1272]
## Feature description

I think it would be interesting to have an editable example in README, like the ones from [Blueprint](https://codesandbox.io/s/nko3k41y60) and [Material](https://codesandbox.io/s/4j7m47vlm4) (however the Material one may be too simple). I tried to run the [example](https://github.com/tajo/fusion-baseui) by @tajo on codesandbox, but had no luck so far. Apparently, the dependencies, as they are today, are too complex for codesandbox, as can be seen [here](https://codesandbox.io/s/github/IgorWilbert/fusion-baseui). Does anyone else thinks that it would be interesting to have a slightly bigger example on README as some sort of showcase? If so, should we aim at making the example by @tajo run on codesandbox or incorporating it as a separate page inside the documentation? Or perhaps creating something new but more simple, just for codesandbox?  Thanks!

**Comment by tajo** [comment]
The more examples, the merrier! CodeSandbox should work; however, without Fusion.js. Do you want to give it a shot?

**Comment by IgorWilbert** [comment]
Nice! Yes, I would like to. I will let you know how it goes :)

**Comment by IgorWilbert** [comment]
Hi @tajo ! Sorry for coming back to you so late, I had a tough week. I tried to follow the instructions to run your [example](https://github.com/tajo/fusion-baseui), but got the following error:
![error](https://user-images.githubusercontent.com/42987854/57969414-041d9100-794d-11e9-8609-be54a0887bc7.JPG)
When I tried to open `https://unpm.uberinternal.com/baseui/-/baseui-5.4.0.tgz#b4606513b264b610e1cabc0347c6a4831d663faf` on the browser, I was asked for a username and password, so I guess we would need to replace `uberinternal.com` dependencies for something public. Besides this, since we will need to remove `fusion.js` and you made a tutorial for your app on `README`, should I start from scratch, maybe using `create-react-app`?

**Comment by chasestarr** [comment]
try pulling the latest master. it should resolve the `unpm` issues

**Comment by tajo** [comment]
@IgorWilbert Oops, my bad. I committed wrong yarn.lock. It's fixed now.

**Comment by IgorWilbert** [comment]
No problem @tajo, now I was able to run the project, thank you for fixing it. Do you have any suggestion about where should I start working to remove fusion? Thanks!

**Comment by tajo** [comment]
I think you can keep Fusion? CodeSandbox has a Next.js template. Fusion is very similar to Next.js so I assume it should work in that environment as well. If not, I would replace Fusion with Next.js. Or there is `create-react-app` template as well. So this would be my preference: 

1. Preserve Fusion
2. Use Next.js template
3. Use CRA template

**Comment by IgorWilbert** [comment]
Hey @tajo ! Just to keep you updated, I started a sandbox with Next.js and uploaded files manually. It automatically shifted to Node.js template, and seems to be working fine, as can be seen [here](https://codesandbox.io/s/elegant-dhawan-b7kgx). I'll review it more carefully soon, as there seem to be some details missing. Thanks!

**Comment by IgorWilbert** [comment]
@tajo I reviewed it and it seems to be fine https://codesandbox.io/s/elegant-dhawan-b7kgx .The console errors are the same that can be seen if you run the project. What would you like me to do with it? Transfer the sandbox to another account, add the link above to `README`, or something else?
