### ISSUE TITLE
Code "compilation" inside documentation

### ISSUE THREAD

**Issue by IgorWilbert** [uber-web/baseui#1273]
## Feature description
I was checking the [Semantic React UI library](https://react.semantic-ui.com/elements/button/#types-button) and I found it amazing how you can edit code and compile it immediately to see the changes in the components. Upon closer inspection, I found that apparently it is all custom-made to work like this, as can be seen [here](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/docs/src/components/ComponentDoc/ComponentExample/ComponentExample.js) and [here](https://github.com/Semantic-Org/Semantic-UI-React/blob/7da1dd029471f653bac513661d27ac5092ef523d/docs/src/examples/elements/Button/Types/index.js). Opening codesandbox every time one wants to edit code is quite annoying in my opinion, so do you think it would be interesting to implement something like this on Base in the near future? Thanks!

**Comment by tajo** [comment]
Yea, I would like that too! We did that for [styletron.org](https://www.styletron.org) while using [react-live](https://github.com/FormidableLabs/react-live). It's fairly straightforward, we just need to define the scope (imports) for every example/component.

cc @gergelyke

**Comment by tajo** [comment]
We have the first component using live-editable example. https://baseweb.design/components/button/
