### ISSUE TITLE
onClick prop on StatefulPopover

### ISSUE THREAD

**Issue by norenma** [uber-web/baseui#1282]
When using StatefulPopover on a clickable element, it propagates the click event and calls the click handler for the outer element.  To able to stop propagation on click on the anchor of a StatefulPopover, it would be nice to have an onClick prop that would pass the event from the anchor, so stopPropagation can be called on it. 

## Feature description
An onClick prop on the StatefulPopover that passes the event created by the anchor. 

The stateless Popover seems to have this functionality.

**Comment by chasestarr** [comment]
Hi @norenma please see the linked PR with discussion. The `onClick` callback is accessible using the `Popover` component. Please create a codesandbox repro if that does not meet your needs.
