### ISSUE TITLE
How to modify fill of an active input field?

### ISSUE THREAD

**Issue by claudio-carmeli** [uber-web/baseui#1293]
I would like to find out how I can have a text input turn e.g. yellow once I click on it. I would expect a "inputFillActive" primitive like many others but it's missing.

## Feature description
An easy and intuitive way to control the fill colour of an input component on click (or whenever it becomes active).

**Comment by chasestarr** [comment]
this can be done with overrides and switching on the value of [$isFocused](https://github.com/uber-web/baseui/blob/master/src/input/types.js#L36). See documentation for how to customize component styles here: https://baseweb.design/theming/understanding-overrides/
