### ISSUE TITLE
Accessibility issues with the Datepicker

### ISSUE THREAD

**Issue by freaksauce** [uber-web/baseui#1304]
## Current Behavior

When using Mac OS Voice Over when you use the keyboard to navigate to the current Datepicker you get the previous month button announced correctly as below:
![Screen Shot 2019-05-22 at 1 38 13 pm 2](https://user-images.githubusercontent.com/5125097/58146255-a795db00-7c98-11e9-9eb8-f884447a1af0.png)

However when you tab to the month or year select controls it simply announces "group" so the user is left with no idea what the control actually is, see below:

![Screen Shot 2019-05-22 at 1 39 53 pm 2](https://user-images.githubusercontent.com/5125097/58146294-b9777e00-7c98-11e9-84a6-7f262eefa739.png)

If you then activate this control to select an option inside the select it doesn't announce that you are inside the list, which item is currently selected or which item is selected when you use the keyboard to change options as below:

![Screen Shot 2019-05-22 at 1 41 12 pm 2](https://user-images.githubusercontent.com/5125097/58146299-bda39b80-7c98-11e9-8a6c-891d5dd535a9.png)

## Expected Behavior

Without the screen reader announcing the month and year or the dropdown option that you are navigating it is impossible for a sight impaired user to use this Datepicker.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.19.1  |
| React   |         |
| browser |         |

- [ ] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by freaksauce** [comment]
I was unaware that you could use the `overrides` prop on `StatefulCalendar` to add a `MonthSelect` aria-label which fixes the issue above, closing issue.

**Comment by gergelyke** [comment]
Thanks for opening this Jon! would you be up for sending a PR fixing the issues mentioned above?

**Comment by jh3y** [comment]
It seems the solution to this issue would require some extra thought 🤔 

The dropdown list is rendered in a list inside a `Popper`. Because that `Popper` is appended to the body, tabbing doesn't take you to the list. You can try to combat this with a custom `mountNode` for the `Popper` that does allow you to tab into the `Popper` anchor. I was unable to tab into the list from there though.
