### ISSUE TITLE
Error: "Could not find module in path..." in Code Sandbox

### ISSUE THREAD

**Issue by bvluong** [uber-web/baseui#1312]
## Current Behavior
Code Sandbox examples from baseui are not able to import baseui module.

![Screen Shot 2019-05-22 at 4 02 25 PM](https://user-images.githubusercontent.com/24781265/58214840-13357380-7cac-11e9-9465-29a78aee5283.png)

![Screen Shot 2019-05-22 at 4 02 31 PM](https://user-images.githubusercontent.com/24781265/58214832-0dd82900-7cac-11e9-8c41-365babcefd58.png)

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.19.2  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by lxe** [comment]
Looks like it's mispublished... top-level files live in dist/ now.

**Comment by lxe** [comment]
Repro:

https://codesandbox.io/s/upbeat-resonance-1iwub

**Comment by gergelyke** [comment]
fixed in 6.19.3 - thanks for the report!
