### ISSUE TITLE
Accordion UI Bug

### ISSUE THREAD

**Issue by GavBaros** [uber-web/baseui#1323]
## Blue border highlighted when open, but when back to being closed, bottom blue border is hidden while the left, right and top borders remain highlighted in blue.
Shouldn't they all be deselected when the accordion closes? 

![uberaccordionuibug](https://user-images.githubusercontent.com/30755017/58379121-6999ff00-7f97-11e9-84fc-f3e46fa439c0.gif)

## Your Environment

I tested this on the Base UI website, accordion section.

| Tech    | Version |
| ------- | ------- |
| Base UI | v?.?.?  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
This is the element's 'focus' indicator. Pressing 'tab' should focus the next accordion panel and display the border. The hidden bottom-border is not ideal, but we should maintain the borders in general
