### ISSUE TITLE
[Textarea] Add support for configuring minimum and maximum height

### ISSUE THREAD

**Issue by austintang** [uber-web/baseui#1348]
Currently there isn't any way to specify the maximum and minimum height that a `Textarea` component can have. As a result, any user can resize the `Textarea` to any length they want. This may result in UI alignment issues in tools that consume the BaseUI `Textarea` component.
![Screen Shot 2019-05-31 at 2 33 55 PM](https://user-images.githubusercontent.com/42187119/58736099-76608d80-83b1-11e9-91e4-97596a6e54c1.png)

**Comment by jh3y** [comment]
This can be achieved with `overrides`. It would mean adding `resize` to the `style` override of `Input` and also providing `minHeight` and `maxHeight` 👍 

```js
<Textarea overrides={{
  Input: {
    style: {
      minHeight:'100px',
      maxHeight: '300px',
      resize: 'both'
    }
  }
}} />
```

I'll create an example for the docs.
