### ISSUE TITLE
NavItem override does not work in SideNavigation component

### ISSUE THREAD

**Issue by timalander** [uber-web/baseui#1366]
## Current Behavior

I forked the example sandbox from the documentation, found here: https://codesandbox.io/s/q1x5h?module=/example.js

I then edited a few of the CSS properties in the `NavItem` style function override.
Example of the forked sandbox with modified styles: https://codesandbox.io/s/side-navigation-with-overrides-qqlpd?module=/example.js

These changes do not propagate to the rendered `NavItem`'s.

## Expected Behavior
The styles found in the override apply correctly to the children `NavItem`'s rendered by the `SideNavigation` component.

## Your Environment
| Tech    | Version |
| ------- | ------- |
| Base UI | v7.0.0  |
| React   | v16.8.6 |
| browser | Chrome 74.0.3729.169 |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by AndrewBarba** [comment]
This is due to some inconsistent dep versions. Its fixed when using latest version of all Base deps
