### ISSUE TITLE
Responsive typography

### ISSUE THREAD

**Issue by illogikal** [uber-web/baseui#1370]
I have created a functionality in my theme file to make the typography styles responsive:

## Feature description
```
const mediaSizes = {
  smallPhone: 320,
  bigPhone: 480,
  tablet: 600,
  bigTablet: 801,
  tabletLaptop: 1025,
  desktop: 1281
}

const makeFontSizeResponsive = fontSize => {
  const fontNumber = fontSize.slice(0, -2)
  const result = {
    [mediaQueries['smallPhone']]: { fontSize: `${fontNumber * 0.7}px` },
    [mediaQueries['bigPhone']]: { fontSize: `${fontNumber * 0.75}px` },
    [mediaQueries['tablet']]: { fontSize: `${fontNumber * 0.8}px` },
    [mediaQueries['bigTablet']]: { fontSize: `${fontNumber * 0.85}px` },
    [mediaQueries['tabletLaptop']]: { fontSize: `${fontNumber * 0.9}px` },
    [mediaQueries['desktop']]: { fontSize: `${fontNumber}px` }
  }
  return result
}
const newTheme = createTheme({
  ...,
  'typography': {
    'font100': {
      'fontFamily': 'Helvetica, Arial, sans-serif',
      'fontSize': '11px',
      'fontWeight': 'normal',
      'lineHeight': '1.45em',
      ...makeFontSizeResponsive('11px')
    },
  ...
}
```
  
However these do not work with the baseui typography classes because the fonts prop is filtered by individual keys, and I believe that the styles are also not deep merged. I could create my own custom typography components and probably will due to time, but I think it would be good to allow this. If there is a better way please advise?

See: https://github.com/uber-web/baseui/blob/master/src/block/styled-components.js#L86

**Comment by jh3y** [comment]
Hey @illogikal 👋 

Are you able to provide a `CodeSandbox` example for what you are trying to achieve. From the code above, the media query keys wouldn't be populating as `mediaQueries` would be `undefined`. However, I'd imagine you have this code running somewhere 👍

**Comment by asherccohen** [comment]
Is there a way to extend mediaQueries? there are way more screen sizes than the 3 values set by BaseUI. I tried with Theme Overrides and I can see the added value to my theme object but then somehow at runtime this is not used in my style.

**Comment by sandgraham** [comment]
> Hey guys, how would you type custom media queries?I've added some to my theme overrides but I get type errors saying my properties don't exist.

This section of the theming guide focuses on extending the default theme with new properties: https://baseweb.design/guides/theming/#customizing-the-theme-type

**Comment by asherccohen** [comment]
Ok but this means my custom mediaQueries will not be part of the existing ones.

To read them from the theme I would have to do:
`theme.customMediaQuery.xxLarge`

instead of:

`theme.mediaQuery.xxLarge`

And on top of that I would have to create my own MediaQuery type instead of using the one from baseUi.

Any suggestion?

**Comment by sandgraham** [comment]
@asherccohen Right now the only way to do something like this would be to create your own theme type that overrides the `mediaQuery` part of our default themes. [Here](https://flow.org/try/#0PTAEE0HsFdQYwIYDtQEsC2AHSAnALqHgBYCmAziaAGY6TqgBGCF0qAdBwFCdXRJx5UkFHBwkEeEgBVS6EgBMAyngCeAGwUAeAMLQyeOjJJypAPgAUASlABvTqFBi80HCiugAvKdsBfANygINQIANYknD48fAJCImIS0rIKAOqoxMrqJDp6BuhGJhbWdg5OLm7WXr4BQVSh4ZG8-ILC8PGS+QoAqhQZGni0SNn6hklm7sWOJM6uoO6VANoAutVgtWER3KqYlABCzCQ78SHYqEh4ZJ629qBk6AhqagBcoEjQ6AwkOH7XcvKob89Xu9Pt8HGoEDgAOYkQFvD5fDacLa7fYAWQUqAQAEVoJ8VJcJrd7k8bv1TpDQaBfv90M99DhyZTwVCYaSGUgKYjkaA9hQOgTrkE7kh8ZBiJ9QJhaNt8KhyKASAAPVD6UCQBgANyEejUKmuDCOJzOZGevIOhsgp3OABofhjsbicCpTWj7Ti8Yighw2Mh5IRSCglZIkH7xfQDK1xJJQAh4Dk6P7jJRkd7NiptqBUSp+R4rg5vWaOraHAbxMdLcbnhN8xwzYcy0abdcHIrmdDYcCEQ4W62Ie2XnCQdcfMWqW7Hc6892C66-g68aOW23WfTGc3QIreyy6WSOZTIpFOHBhKqw6yszmp6XQo2TVOHESHs8AKwABlfi7HfwBoAAbO-P2XZ4AHYAPXLd+wADjA7sNwg1kAE4YNAEc7Tnd0nSrddHxJAByAABalYzIUQSBIFBfVmdBTgAWgAd1QeRiBfd9MEVSxcM-akfwIoiblI8iYxDKjaIYpiiGef9XzYjjAL7VlePtfixEEyjzGopB6MY5jQFA6T2M48CgNARS52UsiKOE9TRO0iTQGg-TZPA+DnlMzFzNUqyNK08TniQxzDIcA9uC9DhKPFFA9EoFQYBwQh03lCNSISUAYpcUl1HJUBoEENQ0jlMhuCVbB8HgE8CDPJRVA0P1c2S9okiqzJ5E0C8kkKb5itwAhjyQU9GtSdJqsoOq2kSJN5EGoheiyNqkw6zgutK3r+om7oSBm-oWlGqNxt+dbNoGVrs3aqxvk4II0sTSKKFS2K42Geh9Eyjlsty-L5Uoq6yCIGA1D9IgEA1SgpUgGVEzkeLMHJIA) is an example.

**Comment by asherccohen** [comment]
Great, that helped. Your example used Flow.
This is the TypeScript version:

```
type BaseBreakpoints = {
  small: number;
  medium: number;
  large: number;
};

type BaseMediaQuery = {
  small: string;
  medium: string;
  large: string;
};

type CustomBreakpoints = {
  xxLarge: number;
};

type CustomMediaQuery = {
  xxLarge: string;
};

export type CustomThemeT = Theme & {
// other custom values
  breakpoints: BaseBreakpoints & CustomBreakpoints;
  mediaQuery: BaseMediaQuery & CustomMediaQuery;
};

export const themedStyled = createThemedStyled<CustomThemeT>();
export const themedWithStyle = createThemedWithStyle<CustomThemeT>();
export const themedUseStyletron = createThemedUseStyletron<CustomThemeT>();
```

It would be nice to have the real Breakpoints and MediaQuery types to avoid having to create them here.

**Comment by sandgraham** [comment]
@asherccohen Ah okay, they are exported in Flow, but not Typescript. Opened #3779.
