### ISSUE TITLE
Font *50 are not bold anymore with v7

### ISSUE THREAD

**Issue by parigi-n** [uber-web/baseui#1386]
## Current Behavior

https://baseweb.design/components/block/#block-with-font-customization
Font with 50 are the same as 00 font
ex: font200 is visually the same as font250

## Expected Behavior
Font with 50 are supposed to be bold as seen in https://v6.baseweb.design/components/block/#block-with-font-customization
ex: font250 should be the same size as font200 but bold

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v7.10 |
| React   |  16.8.6 |
| browser |    Chrome 74     |

**Comment by gergelyke** [comment]
Hello Nicolas! Thank you for opening this ticket! This change was introduced as part of a bigger visual overhaul in the design system - if you want to get the old look and feel back, you can customize the theme: https://baseweb.design/theming/custom-themes/#creating-a-custom-theme

**Comment by parigi-n** [comment]
Hi Gergely,

First, thank you for this quick answer. And thanks to all the contributor of BaseUi for this awesome library.

Ok I understand, so the old *50 font are just there to keep compatability with old versions ?
Maybe I could be less confusing to remove them from the font property example ?

**Comment by gergelyke** [comment]
The design system changed the font ramp too, so some of them are left there for compatibility reasons, some changed in the design system too. We are sorry for the confusion it created!

**Comment by parigi-n** [comment]
Nothing to be sorry about, thank you for your clear answer.
