### ISSUE TITLE
Kitchen Sink Demo

### ISSUE THREAD

**Issue by lxe** [uber-web/baseui#139]
The storybook is great, but I'd like to see a kitchen sink demo or a couple of examples of how to structure the apps. For example:

https://material-ui.com/page-layout-examples/
https://material-ui.com/page-layout-examples/dashboard/
https://getbootstrap.com/docs/4.0/examples/
https://getbootstrap.com/docs/4.0/examples/dashboard/
https://github.com/ant-design/examples

etc...

**Comment by gergelyke** [comment]
Closing this, as we have a few examples at https://baseweb.design/getting-started/learn/
