### ISSUE TITLE
HeaderNavigation padding cannot be overridden with Styletron styled(...)

### ISSUE THREAD

**Issue by wilbertthelam** [uber-web/baseui#1408]
For the HeaderNavigation component, using BaseUI Styletron styled(HeaderNavigation, { padding: '5px 20px'}), I can't override the default padding from BaseUI without using !important.  It looks like the class ordering seems incorrect.

## Current Behavior

Padding is set to padding-top: 12px and padding-bottom: 12px.

## Expected Behavior

Padding should be set to padding top/bottom: 5px and padding right/left: 20px.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.20.0  |
| React   |    16.8.2    |
| browser |      Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)   |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hi @wilbertthelam - this is how you can do it: https://codesandbox.io/s/header-navigation-basic-usage-nnvlk
