### ISSUE TITLE
[Layer] Expose LayersManager children and host styling

### ISSUE THREAD

**Issue by austintackaberry** [uber-web/baseui#1412]
### Problem

I recently removed all z-indexing from my app and converted to the Layer API which is pretty neat!

However, there was one styling issue that caused some problems for me. The fact that the `LayersManager` throws all of the `Layer`s into a `div` that cannot be styled:
https://github.com/uber-web/baseui/blob/master/src/layer/layers-manager.js#L29

This caused many issues for me, but one specific one is using the `LayersManager` component in a flex container: https://codesandbox.io/s/layer-basic-usage-re30i

One other issue I recently ran into is not being able to set `overflow: scroll` for any descendants of `LayersManager` because I cannot set the height of the `LayersManager` `div`: https://codesandbox.io/s/layer-basic-usage-o1y78

### Proposed Solutions

1. Expose styling for the host div and also the div that holds children
2. Don't put the children in a div, expose styling to host div

**Comment by jh3y** [comment]
Hey @austintackaberry 👋 

Could you potentially achieve what you want by not using a `LayersManager` and using an overridden `Block`? Then you could use that `Block` as a custom `mountNode` for `Layer`?

That might be a quick work around.

**Comment by austintackaberry** [comment]
Hey @jh3y!

I was able to find workarounds for my usecase. I only added the problems I faced and the codesandboxes in order to bolster my opinion that this feature is useful 🙂

**Comment by gergelyke** [comment]
@austintackaberry @jh3y should we close this?

**Comment by austintackaberry** [comment]
It doesn't matter to me, but shouldn't it stay open until the feature is implemented?

**Comment by austintackaberry** [comment]
Thanks for jumping on this! Is there a way for me to see which version will include this feature?
