### ISSUE TITLE
[Select] - Drop down menu is 1px misaligned to the left

### ISSUE THREAD

**Issue by Mikewaite** [uber-web/baseui#1431]
As a designer, I was looking at the select component and I noticed that the drowdown menu is 1px off to the left. 

https://imgur.com/bskQcrD

## Current Behavior

When opening a select component, the dropdown menu is 100% the width of the select width, but aligned 1px to the left.

## Expected Behavior

The dropdown menu should be aligned properly.

## Your Environment

This visual bug is found on the demo page: https://baseweb.design/components/select/

| Tech    | Version |
| ------- | ------- |
| Base UI | v?.?.?  |
| React   |         |
| browser |         |

- [X ] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by jh3y** [comment]
I dug into this issue and was able to replicate at certain sizes 👍 

Misalignment tends to happen when the actual size of the element is a fraction of a pixel. On line `908` of `select.js`, `offsetWidth` is used. To be more accurate `getBoundingClientRect().width` could be used. However, this is only to factor for widths that aren’t whole pixels ( For example `576.4px` ). I think these are potentially then rounded by `styletron` before `Popper.js` calculates the offset.

I was able to override the width with a fraction of a pixel.
