### ISSUE TITLE
[StatefulDatepicker] Erratic month browsing behavior after date selection

### ISSUE THREAD

**Issue by houmark** [uber-web/baseui#1470]
## Current Behavior

When a `StatefulDatepicker` is being used with `minDate` and `maxDate` browsing partly stops working after having selected a date.

This is my configuration:

```javascript
<StatefulDatepicker
                  placeholder="YYYY/MM/YY"
                  minDate={addDays(new Date(), 1)}
                  maxDate={addDays(new Date(), 31)}
                  highlightedDate={addDays(new Date(), 1)}
/>
```

**To reproduce:** Open date picker, click a date. Datepicker closes. Reopen the date picker. Try browsing on to the next month with the arrow button/icon. It may work. It may not. Try browsing back one month again. It seems that when you have just around 1 month of accepted selection range, the date picker starts having problems with go back and forward using the arrows.

Interestingly it is possible to change month in the "dropdown" in the middle without any issues, but that dropdown also shows months in the history that in theory should not be displayed according to the `minDate` setting.

## Expected Behavior

Normal month browsing no matter if I already selected a date once.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v7.8.0  |
| React   |    16.8.6     |
| browser |    Chrome 75.x     |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by rohit012** [comment]
I think this check in `renderNextMonthButton` in file - `calendar-header.js` is causing disabling of the button. https://github.com/uber-web/baseui/blob/6389c9b3e3044ba983487e1e22189b05a3f4158c/src/datepicker/calendar-header.js#L112

Probably we can get rid of this check. Shouldn't the check above that - `monthDisabledAfter` function take care of enabling and disabling the next button and . May be I am missing a specific use case?

**Comment by houmark** [comment]
@rohit012 Thanks for looking into this.

In my case, I did have a `minDate` and `maxDate` per my example above and while I have no dug into the code, maybe the `renderNextMonthButton` is choking while figuring out if it should enable that next button in relation to the `maxDate` set?
