### ISSUE TITLE
[Button] Show props not correct when using typescript

### ISSUE THREAD

**Issue by ancs21** [uber-web/baseui#1485]
Hello guys,

## Current Behavior

This error as picture.
![button_error](https://user-images.githubusercontent.com/9210835/60324981-b5b0d880-9975-11e9-8dd1-909de293f169.png)

## Expected Behavior

This correct need: `compact`, `default`, `large`

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.0.2  |
| React   |    16.8.6     |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hey! we have an open PR for this here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36504

Please follow that ticket for the fix - I am going to close this one here
