### ISSUE TITLE
Demo integrating form components with ReduxForm

### ISSUE THREAD

**Issue by arkadyp** [uber-web/baseui#150]
It would be super helpful to have a few canonical examples of how to integrate the form components with ReduxForm. 

Additionally, it may be worth considering adding some ReduxForm HOC to wrap the components:
```js
// Wrapped component
export function ReduxFormTextInput(props) {
  const {
    input: {onChange, value},
    placeholder,
    disabled,
    ...otherProps
  } = props;
  return (
    <TextInput
      onChange={onChange}
      value={value}
      placeholder={placeholder}
      disabled={disabled}
      {...otherProps}
    />
  );
}

// Example use:
<Field
  component={ReduxFormTextInput}
  placeholder="placeholder"
  name="fieldName"
/>
```
If BaseUI doesn't expose these wrappers, I think that each project that wants to integrate with ReduxForm will need to reimplement this boilerplate.

I wanted to kick off a discussion of where these examples/wrappers belong. Maybe it makes more sense to create a separate `baseui-reduxform` repo to prevent bleeding concerns?

**Comment by kahwee** [comment]
I use `redux-form` a lot too and it will be nice to have a `baseui-redux-form` repo that exposes the render methods.

**Comment by Warbring3r** [comment]
Warning: If onChange from redux-form as a HoC is naively passed through to a StatefulSelect component, the first time the StatefulSelect element is changed, the value will not be updated. If the redux-form onChange event is not passed through, the StatefulSelect works as expected. The current fix is to not pass the onChange event through from redux-form as a HoC to Base-UI, but I don't think that's ideal.

**Comment by Warbring3r** [comment]
Here is how we got BaseUI and redux-form working nicely together.

First, the redux-form wrapper:
`
         <Field
              name="trailerType"
              label={'Trailer Type*'}
              component={ReduxFormSelectField}
              placeholder={'Select one'}
              required={true}
              options={trailerOptions}
              maxDropdownHeight={'200px'}
              validate={[validateTrailerType]}
              labelKey="label"
              valueKey="id"
              onChange={this.trailerChange}
              searchable={false}
              selectOrSearch={'select'}
              $style={{ width: inputWidth }}
              overrides={{
                DropdownContainer: {
                  style: {
                    width: '280px',
                  },
                },
              }}
            />
`

Then, the HoC around BaseUI:

`
// @flow
import React from 'react';
import { Select, TYPE, type OnChangeParamsT } from 'baseui/select';
...
type ReduxFormSelectProps = ReduxFieldProps & Props;
export function ReduxFormSelectField(props: ReduxFormSelectProps) {
  const {
    input: { onChange, value: trueValue },
    label,
    meta: { touched, error },
    placeholder,
    disabled,
    options,
    selectOrSearch,
    $style,
    ...otherProps
  } = props;
  const uiErrorState = touched && error;
  const type = selectOrSearch === 'select' ? TYPE.select : TYPE.search;

  return (
    <Main $style={$style || {}}>
      <Label>{label}</Label>
      <Container>
        <Select
          options={options}
          disabled={disabled}
          placeholder={placeholder}
          error={uiErrorState}
          type={type}
          onChange={({ value }) => onChange(value)}
          value={trueValue}
          {...otherProps}
        />
      </Container>
      {touched && error && <Error>{error}</Error>}
    </Main>
  );
}

export default ReduxFormSelectField;
`

The key is using a stateless component (NOT stateful) and passing through the redux-form onChange inside the BaseUI onChange event, otherwise they collide and two redux actions get fired.

**Comment by chasestarr** [comment]
going to close this issue since it seems like folks have developed some effective patterns. this post will be still searchable and i've created a stack post for folks searching there

**Comment by leyanlo** [comment]
@Warbring3r’s solution was super helpful, but we ran into issues around redux-form’s default value being an empty string:
https://redux-form.com/8.2.0/docs/api/field.md/#-code-input-value-any-code-

This ended up being incompatible with the Base Select component, and we would not see the placeholder (#1252). We also removed the inline function declaration to avoid memory leaks. For those who might find this helpful, our HOC ended up looking like this:
```js
// @flow
import * as React from 'react';
import {Select} from 'baseui/select';
import type {FieldProps} from 'redux-form';
import type {PropsT} from 'baseui/select';

type ReduxFormSelectProps = FieldProps & PropsT;
export class ReduxFormSelect extends React.PureComponent<ReduxFormSelectProps> {
  onChange = ({
    value: v,
  }: {
    value: $PropertyType<$PropertyType<FieldProps, 'input'>, 'value'>,
  }) => this.props.input.onChange(v);

  render() {
    const {
      input: {value},
      ...restProps
    } = this.props;
    return (
      <Select
        onChange={this.onChange}
        {...(value !== '' ? {value} : {})}
        {...restProps}
      />
    );
  }
}
```

And our usage looks like:
```js
<Field
  component={ReduxFormSelect}
  name="equipment"
  options={[
    {id: 'van', label: 'Dry Van'},
    {id: 'reefer', label: 'Reefer'},
  ]}
/>
```
