### ISSUE TITLE
Add Typescript types to DefinitelyTyped project

### ISSUE THREAD

**Issue by ajbogh** [uber-web/baseui#151]
Most of the global developers using a typed language are using Typescript (43% of developers on npm according to a recent conference presentation from the npm team). It would benefit the project to also support Typescript or conversation to Typescript completely instead of Flow.

**Comment by fadeojo** [comment]
@gergelyke what would it take to get this done?

**Comment by fadeojo** [comment]
@gergelyke I tried to use dts-gen in this library but the converter doesn't work well with EMS modules. I can help if someone can help with getting started.

**Comment by tajo** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/baseui
