### ISSUE TITLE
Override default property values

### ISSUE THREAD

**Issue by simPod** [uber-web/baseui#1515]
I have not found a way how to globally set default value for eg. input size to `SIZE.compact`. Is there a way? I wonder that it could be possible via theming.

**Comment by gergelyke** [comment]
hi @simPod! yes, that makes perfect sense - we were thinking about providing a `compact` theme. Any chance you'd be up for contributing it?

**Comment by simPod** [comment]
@gergelyke Like `compact` theme in addition to `light` and `dark`? I was rather thinking that there is no prop to override to pass to `createTheme`, that would be sufficient.

**Comment by gergelyke** [comment]
that makes sense too - can you send a draft PR to see how that would look, let's say with the button first?

**Comment by simPod** [comment]
Still thinking about it. Now I came across the problem that I want to modify this property https://github.com/uber-web/baseui/blob/5b0ed2308a96c15f12352e2b14d327b173627dfd/src/input/styled-components.js#L335, also globally. IMO it's related to the ultimate solution.
