### ISSUE TITLE
TS definitions not up to date

### ISSUE THREAD

**Issue by simPod** [uber-web/baseui#1517]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a176b84419c707516be04a8397cdd90e1f49ed38/types/baseui/index.d.ts#L28

It says `LightThemePrimitives` are exported. But `lightThemePrimitives` [are exported](https://github.com/uber-web/baseui/blob/5b0ed2308a96c15f12352e2b14d327b173627dfd/src/index.js#L21) actually. I can send PR, just not sure I'm right.

**Comment by jh3y** [comment]
Hey @simPod 👋 
Thanks for spotting this. Please feel free to open a PR on `DefinitelyTyped` 👍

**Comment by jh3y** [comment]
Closing as the PR was merged 🙌
