### ISSUE TITLE
Seemingly invalid errors when using `styled('div')`

### ISSUE THREAD

**Issue by vicapow** [uber-web/baseui#1535]
## Current Behavior

```
Cannot call `styled` because: Either  string [1] is incompatible with  `React.ComponentType` [2] in type argument `Base`. Or  string [1] is incompatible with  `React.ComponentType` [3] in type argument `Base`.Flow(InferError)
```

## Expected Behavior

no error

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.4.0  |
| React   |    v16.8.2     |
| browser |    Chrome     |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hi @vicapow - can you please provide a full example and the flow version you are using in your project?

**Comment by vicapow** [comment]
Taking a look at the definition for styled, seems pretty clear this case is missing: https://github.com/uber-web/baseui/blob/master/src/styles/styled.js#L34

**Comment by gergelyke** [comment]
would you mind sending a PR fixing it?

**Comment by vicapow** [comment]
I can. Also, are you busy today for a chat? I had some ideas on how we can better detect and prevent these types of issues in the future.

**Comment by gergelyke** [comment]
sounds great, thanks!
