### ISSUE TITLE
How to style a Button inside a ButtonGroup?

### ISSUE THREAD

**Issue by houmark** [uber-web/baseui#1537]
## Current Behavior

I'm trying to style a Button inside a ButtonGroup. I have a `StatefulButtonGroup` in mode `radio` with two options. The idea is to have one in a positive color and one in a negative color, to use as a approve/reject situation.

If I have my buttons outside of a group, then I can style for example the button background without issues, but once they are inside the button group, it seems to not be possible to style anything at all. Only enhancers work.

Slightly off-topic, but In relation to this, is there a simple way to pull out possible overrides for a component right inside my code? Being a noob in Baseweb, I seem to struggle with understanding what I can and cannot do or what are the possible styles or default styles applied to an element? I was thinking it could be somewhat cool to be able to add a prop (for example `debug`) to have the console output valuable information for the dev to quickly understand what can be done, instead of trial and error or swapping to docs to try to understand better.

## Expected Behavior

Be able to style each button in the group according to my need.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.4.0  |
| React   |    16.8.2     |
| browser |     Chrome 75.x    |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hi @houmark - the reason it won't work, because we override the button styles inside the button-group component ourselves.

For your use-case, I'd recommend using the button component instead of the button-group - would that work?

Re your second question, we are working on a new component playground, that - hopefully - will address your issue. We'll get to that in a week or two :)

I am closing this ticket, but feel free to re-open if you have further questions!

**Comment by houmark** [comment]
I guess I can just do singular click events on each button and smash them together with another override. Should this not be kept open as a feature request to allow buttons to be overridden inside a button group?

Looking forward to the playground, even though I would find it even more useful to be able to have the component itself spit out useful info, but I understand that would also add to the package size (though maybe this could be only in "dev" mode).

**Comment by houmark** [comment]
Adding to this, my reason for suggesting this is that powerful and flexibility is also equal to a deeper learning curve and the adoption of Baseweb may suffer from that. Being able to see what I could easily change in overrides right where I am working, would help me to better understand the possibilities.
