### ISSUE TITLE
<Select /> Element printing attribute-related console errors

### ISSUE THREAD

**Issue by aj-4** [uber-web/baseui#1542]
throws console errors:
```Warning: Received `true` for a non-boolean attribute `$clearable`.

If you want to write it to the DOM, pass a string instead: $clearable="true" or $clearable={value.toString()}.```

```
Received `false` for a non-boolean attribute `$disabled`.

If you want to write it to the DOM, pass a string instead: $disabled="false" or $disabled={value.toString()}.
```

```
Received `false` for a non-boolean attribute `$error`.

If you want to write it to the DOM, pass a string instead: $error="false" or $error={value.toString()}.
```

etc...

I'm just using the <Select /> *controlled example* from 
https://baseui.netlify.com/components/select/

## Current Behavior

5+ console errors with the messaging above, completely fills console.
Worth noting that component functionality seems fine.

## Expected Behavior

No console errors

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.14.2 |
| React   | 16.8.6 |
| browser | Chrome |

- [ x ] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by u-juyang** [comment]
Noticed the same behavior in Block component too.

**Comment by chasestarr** [comment]
can you reproduce the error in a codesandbox?

**Comment by u-juyang** [comment]
I was able to find the root cause of the warnings. They were caused by passing a wrong type of field to startEnhancer on Button component. The startEnhancer expects a ReactNode, but we passed a React Component class instead.

The stacktrace was a bit confusing, nevertheless sorry for the noise.

It works fine in codesandbox @chasestarr I didn't see any error / warning in codesandbox

**Comment by chasestarr** [comment]
no worries - this is an warning likely related to styletron. react plans to release better logging tools in their next version, allowing styletron to improve.  that should help track down the issue more effectively
