### ISSUE TITLE
Docs [Mobile view]  Missing change theme icon

### ISSUE THREAD

**Issue by qqingvarqq** [uber-web/baseui#1546]
## Current Behavior
It's not possible to set a dark theme when you use baseweb docs on mobile devices. (Missing change theme icon)
<img width="321" alt="1" src="https://user-images.githubusercontent.com/13419634/61116497-39ea7c00-a49d-11e9-8a1c-61301d07f1a2.png">
Also, padding looks weird: default header and when you use search.
<img width="324" alt="2" src="https://user-images.githubusercontent.com/13419634/61116702-a1083080-a49d-11e9-89f1-6b2a70ee1dfd.png">

## Expected Behavior
Should be possible to set a dark theme on mobile devices. It would be possible to place the change theme icon inside the header or inside the menu.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v?.?.?  |
| devices | all devices with small view iPhone 5s, pixel XL etc |

- [X] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by IgorWilbert** [comment]
Hi! I would like to work on this issue. Thanks :)

**Comment by gergelyke** [comment]
sounds great, thanks @IgorWilbert !
