### ISSUE TITLE
Prop overrides should accept a function

### ISSUE THREAD

**Issue by gergelyke** [uber-web/baseui#1552]
Currently, you can pass a function into `style` and `component` overrides but not props. For example:

<Component overrides={{  props: { 'data-test': 'foo' } }} />

works but

<Component overrides={{  props: props => ({ 'data-test': 'foo' }) }} />

doesn't.

This makes it inconsistent with `style` and `component` overrides and prevents some use-cases like adding BEM class names for different internal states of the component.

**Comment by qqingvarqq** [comment]
I want to attempt this one
