### ISSUE TITLE
Cleanup and document ENV flags for doc builds

### ISSUE THREAD

**Issue by gergelyke** [uber-web/baseui#1553]
Currently, we use the following ENV vars for building the doc site:

- BUILD_ENV
- WEBSITE_ENV
- NODE_ENV

Let's settle on one, and document it. Please be aware, that the extract-react-proptypes package is depending on `WEBSITE_ENV` https://github.com/atlassian/extract-react-types/blob/master/packages/extract-react-types-loader/index.js#L38

**Comment by jh3y** [comment]
@gergelyke @tajo After taking a proper look at this I'm not 100% sure on what to do here. `NODE_ENV` is of course used in a variety of places.
`WEBSITE_ENV` can't be dropped if it's relied on by a third party package?
`BUILD_ENV` is being used for `Netlify` and `Docker`. Not sure if `BUILD_ENV` could be swapped out for `NODE_ENV` here.

**Comment by gergelyke** [comment]
Let me send a draft pr with the idea

**Comment by gergelyke** [comment]
Actually, this should do the trick https://github.com/uber-web/baseui/pull/1565
