### ISSUE TITLE
Height of StatefulInput vs. StatefulSelect in Safari

### ISSUE THREAD

**Issue by houmark** [uber-web/baseui#1576]
## Current Behavior

I have a simple filtering UI with a `StatefulSelect` and a `StatefulInput` next to each other plugged inside a `Block` grid (I also tried this with the `FlexGrid` with the same result). Noticed that the `StatefulInput` renders 4px taller than the `StatefulSelect` in Safari (latest 12.1.1).

I've created this CodeSandbox, based on the Block demo, to show how this is happening.

Demo: https://codesandbox.io/s/block-with-grid-usage-87gle

## Expected Behavior

UI components should render the same height and be consistent across browsers.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.6.1  |
| React   |    16.8.2     |
| browser |    Safari 12.1.1     |
| browser |    Chrome 75.x     |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment]
In 8.7.0 the height is no longer the same in Chrome for `StatefulSelect` vs. `StatefulInput`.

Interestingly it seems that in Chrome the `StatefulSelect` is 44px and in Safari it's 48px tall.

`StatefulInput` is 48px in Chrome and 52px tall in Safari. This is with standard default `size` applied.

#1564 seems to be the reason for this change in height.

**Comment by houmark** [comment]
The Chrome issue is not an issue with standard fields. I had an beforeEnhancer with a 18px icon that made the field taller, but even with standard fields the issue is still present in Safari.

**Comment by jh3y** [comment]
I've had a look into this via the `storybook`.

The `StatefulSelect` and `StatefulInput` are the same `height` in `Chrome` and `Safari`. However, that size differs between the browsers. Seems there's a `margin` being included in `Safari` on the `input` itself. `margin: 0em` in `Safari` didn't seem to be doing what it was saying.

I've opened a PR for this 👍
