### ISSUE TITLE
Button with endEnhancer onClick issue

### ISSUE THREAD

**Issue by houmark** [uber-web/baseui#1578]
## Current Behavior

I have a `Button` which has an endEnhancer, to show an icon. The button has an `onClick` event to update a state. If I click the button itself, then it will set the `value` of the `Button` no problem.

If I click the endEnhancer icon, then it will still run the `onClick` event from the button, but it the value will be `undefined`.

What is the correct use of this combo or is there a bug when using an endEnhancer? Should it not inherit the `value` of the button, if it inherits the `onClick` event?

Here's a demo with an alert. Try clicking the button and precisely on the icon: https://codesandbox.io/s/button-with-endenhancer-doxgi

## Expected Behavior

That clicking the button itself or the endEnhancer produces the same event / outcome.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.6.1  |
| React   |   16.8.2      |
| browser |    Chrome 75.x     |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
this seems like a bug to me - what do you think @chasestarr @tajo @sandgraham ?

**Comment by sandgraham** [comment]
This is how [event capturing & bubbling](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events#Bubbling_and_capturing_explained) works by default in the browser.

I don't think we should change/hide this behavior. There may be legitimate use cases for allowing normal event capturing within an enhancer (a nested checkbox perhaps). The `onClick` still has context on which button was clicked so I don't think this behavior limits folks. If you do need to grab something from the button element instance related to the event, you can always use the event object to grab the parent element it or use a ref.

**Comment by houmark** [comment]
I understand fairly well how event bubbling and capturing works. Initially I had a button where I wanted to display a different icon depending on state and even make it possible to clear the state with the click of the icon. I was struggling with capturing the parent event on the icon though (still don't know how to get that) and changed course, but now this has turned into a bug for me, as clicking the icon actually will set to `undefined` which is not what one expects.

So until you decide if this should work differently without overwriting in the handler, could you point me to how I capture the `Button` click event inside the enhancer to keep it the same state if someone clicks the icon? Ref is an option, but if there's a simpler way I'd love to see an example (and this should maybe be added to the docs as well, as this exact use case could lead people into unwanted behavior without noticing it).

**Comment by tajo** [comment]
Yea, I don't think this is a bug. Why to use DOM to pass the value if you can pass it just by JS? What's the whole/bigger use case?

**Comment by houmark** [comment]
The situation is that simply adding an `endEnhancer` to show an icon within a button breaks the click event if you click on the icon. So while this may not be something baseui should automatically handle, there should be an example in the docs on how to get the value from the parent button inside the enhancer.... imho... I've struggled (and still didn't figure out) how to avoid to get `undefined` when clicking the icon.

**Comment by tajo** [comment]
You should probably just avoid using `event.target` altogether. As @sandgraham said:

> The onClick still has context on which button was clicked.

So you can use that. `endEnhancer` accepts any React component, it could be multiple nested DOM elements, so you would have to do some recursive search trying to find the button or add a ref to the button. However, you can just do this: https://codesandbox.io/s/button-with-endenhancer-mgc28

**Comment by houmark** [comment]
So basically the change is as simple as using `event.currentTarget.value` instead of `event.target.value`. Clicking the icon does nothing and I could add any component there with its own `value` and `onClick` or inherit as needed in my use case.

Sometimes I guess it's okay to feel a little stupid :/
