### ISSUE TITLE
[Avatar] styled component prop types are too restrictive

### ISSUE THREAD

**Issue by chasestarr** [uber-web/baseui#1582]
StylePropsT ([link](https://github.com/uber-web/baseui/blob/master/src/avatar/types.js#L11-L14)) is an 'exact' type and will not allow for children to be provided to the component. My suspicion as to why this error is not surfaced in baseui source code is because of wrapping in overrides code

```js
import { StyledInitials } from 'baseui/avatar';
const Initials = withStyle<typeof StyledInitials>(StyledInitials, {color: 'blue'});

function MyAvatar() {
  return <Initials>name</Initials>; // flow errors here
}
```

**Comment by gergelyke** [comment]
@chasestarr should we mark this one as "good first issue", what do you think?
