### ISSUE TITLE
Reason for having multiple SIZE

### ISSUE THREAD

**Issue by simPod** [uber-web/baseui#1583]
I'm trying to get to know the baseui better. Encountered multiple SIZE enums.

https://github.com/uber-web/baseui/blob/c56098a61219393cd2b00278b7d324a1c1d9f974/src/modal/index.d.ts#L6  
https://github.com/uber-web/baseui/blob/c56098a61219393cd2b00278b7d324a1c1d9f974/src/input/index.d.ts#L14  
https://github.com/uber-web/baseui/blob/c56098a61219393cd2b00278b7d324a1c1d9f974/src/button/index.d.ts#L12

Why is it so? Should I import two `SIZE`s when having Input and Button in one component?

**Comment by chasestarr** [comment]
distinctive size enums allows for them to diverge without causing migration pain for consumers

**Comment by simPod** [comment]
@chasestarr so if I understand correctly it is expected for them to be different in the future and not the other way around?

**Comment by chasestarr** [comment]
yes - suppose we want to add a new size, but only for buttons

**Comment by simPod** [comment]
Thanks for info!
