### ISSUE TITLE
Toast's onClose handler doesn't work well with explicit state management

### ISSUE THREAD

**Issue by NameFILIP** [uber-web/baseui#1600]
Approach 1 doesn't work (2 elements are closed on each click).
Approach 2 works, but is a bit hacky.

```javascript
import * as React from "react";
import { Toast, KIND } from "baseui/toast";
import {
  Button,
  SIZE as BUTTON_SIZE,
  KIND as BUTTON_KIND
} from "baseui/button";

export default class Test extends React.Component {
  state = {
    notifications: [
      { message: "1", type: "negative" },
      { message: "2", type: "warning" },
      { message: "3", type: "positive" },
      { message: "3", type: "negative" },
      { message: "2", type: "warning" },
      { message: "1", type: "positive" }
    ]
  };
  closeNotification = index => {
    this.setState(state => ({
      notifications: [
        ...state.notifications.slice(0, index),
        ...state.notifications.slice(index + 1)
      ]
    }));
  };

  render() {
    return (
      <React.Fragment>
        {this.state.notifications.map((notification, index) => {
          return (
            <Toast
              closeable
              kind={notification.type}
              // Approach 1
              onClose={() => this.closeNotification(index)}
              // Approach 2
              // overrides={{
              //   CloseIcon: {
              //     props: {
              //       onClose: () => this.closeNotification(index)
              //     }
              //   }
              // }}
            >
              {notification.message}
            </Toast>
          );
        })}
      </React.Fragment>
    );
  }
}
```

https://codesandbox.io/embed/toast-notification-basic-usage-giwmi

**Comment by gergelyke** [comment]
hi!

you have to add a key to the `Toast`s if you want to handle the state yourself. Something like this should work:

```js
<Toast
  key={notification.message + notification.type}
  closeable
  kind={notification.type}
  onClose={() => this.closeNotification(index)}
  // overrides={{
  //   CloseIcon: {
  //     props: {
  //       onClose: () => this.closeNotification(index)
  //     }
  //   }
  // }}
>
  {notification.message}
</Toast>
```

**Comment by NameFILIP** [comment]
@gergelyke the Approach 1 still breaks once you get to two items with the same message + type. Try clicking on the first 3: https://codesandbox.io/embed/toast-notification-basic-usage-giwmi

**Comment by gergelyke** [comment]
> @gergelyke the Approach 1 still breaks once you get to two items with the same message + type. Try clicking on the first 3: https://codesandbox.io/embed/toast-notification-basic-usage-giwmi.
> The Approach 2 works.

Yeah, those keys should be unique - may doing `key={notification.message + notification.type + index}`

**Comment by NameFILIP** [comment]
@gergelyke It still behaves randomly after adding the `index` (click on the first number 3): https://codesandbox.io/embed/toast-notification-basic-usage-giwmi

Also, it works well when not passing `onClick`, but doing it via overrides, which suggest that the issue is in the component implementation. Would it make sense to reopen the issue?

**Comment by NameFILIP** [comment]
oh, actually, my override is incorrect and is not doing anything, it should be `onClick` instead of `onClose`, but all other points still valid

**Comment by NameFILIP** [comment]
👋 Would it make sense to reopen the issue?

**Comment by NameFILIP** [comment]
Hello, I understand that it looks good when there are less open issues on Github, but the problem still exists and I think the issue can be reopened.

**Comment by gergelyke** [comment]
@NameFILIP it's not an issue with the component itself, but how you assign unique keys to the Toasts you create - if I am correct. This approach, for example, seems to be working: https://codesandbox.io/s/toast-notification-basic-usage-3kt4o

Is there anything stopping you from using the stateful version?

**Comment by NameFILIP** [comment]
In this case, I will have to add a `uuid` property to the notification which is an overhead (might be not the worst thing to add though). The override works for me, so I'm probably going to keep it like that.

Notifications are added to the state (array of notifications) on some failure actions. This state is passed to the component and displayed. On clicking close I want to hide notification and remove it from the state. I don't know what exactly do you mean by using the stateful version, but when I tried that the notification was successfully hidden, but was not removed from the state.
