### ISSUE TITLE
Toast's close button is misaligned

### ISSUE THREAD

**Issue by NameFILIP** [uber-web/baseui#1601]
The "x" button should probably be in the middle of the line.
![image](https://user-images.githubusercontent.com/834796/61677065-05539d00-acb3-11e9-8b25-f2b8af1127ae.png)

**Comment by gergelyke** [comment]
Hi Filip,

thanks for opening this issue! The reason for that is to make sure, that for longer texts too it stays on top.

@nguyensomniac can you verify that please?

<img width="369" alt="Screen Shot 2019-07-23 at 9 23 57 AM" src="https://user-images.githubusercontent.com/2174968/61729244-a3834980-ad2b-11e9-81c7-c946589f2e57.png">

**Comment by nguyensomniac** [comment]
Yes, @gergelyke is right—although we could probably do with 2px padding to align with the first line.
