### ISSUE TITLE
Add support for RTL languages

### ISSUE THREAD

**Issue by zt-uber** [uber-web/baseui#1603]
## Feature description
Add support for language direction in baseui components. In particular, when an element has a left/right padding or margin, the left/right values should be swapped so mirrored elements appear correctly.

## Example

1. Navigate to the [select component](https://baseweb.design/components/select/)
2. In console set `document.dir = "rtl"`
3. Observe that the cursor is up against the right edge with no padding

**Comment by gergelyke** [comment]
hi @zt-uber ! did you experience any issues with components other than the select?

**Comment by zt-uber** [comment]
@gergelyke The form I was working on involved the Input and Select components. My only issue was with Select. Don't know if the other components work out of the box for RTL, but it would be prudent to do a quick audit of the codebase for paddingLeft, paddingRight, etc. while resolving Select.

**Comment by gergelyke** [comment]
@zt-uber thanks!  any chance this is something you could contribute to base web?

**Comment by zt-uber** [comment]
@gergelyke Yeah, I can dig into it some more and see how large of an undertaking it is, and at minimum fix it for Select.

**Comment by gergelyke** [comment]
sounds great, thank you!

**Comment by gergelyke** [comment]
closing this in favour of https://github.com/uber-web/baseui/issues/1678
