### ISSUE TITLE
Modal Body warning <div> cannot appear as descendant of <p>

### ISSUE THREAD

**Issue by zifahm** [uber-web/baseui#1634]
## Current Behavior

```Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>```
I checked inside the modal body
```js
export const ModalBody = styled<{}>('p', ({$theme}) => ({
  ...$theme.typography.font300,
  color: $theme.colors.foregroundAlt,
  marginTop: $theme.sizing.scale600,
  marginLeft: $theme.sizing.scale800,
  marginRight: $theme.sizing.scale800,
  marginBottom: $theme.sizing.scale700,
}));
```
## Expected Behavior
Modal body needs to be a div tag.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.11.0  |
| React   |   16.8.6      |
| browser |  chrome 75.0.3770.142       |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment]
Seeing the same in my end! Seems to be a regression introduced in #1627

**Comment by zifahm** [comment]
@houmark  yup it was changed into a p in last commit https://github.com/uber-web/baseui/pull/1627/commits/d24846d868412bc37ecc1aec97b41cc9f528c1a2
