### ISSUE TITLE
Toast content overflow

### ISSUE THREAD

**Issue by NameFILIP** [uber-web/baseui#1658]
![image](https://user-images.githubusercontent.com/834796/62095613-9374e800-b29e-11e9-9c39-4fd24e20bf80.png)

Something like `overflow:scroll` so that a close button is visible can be a better UX.

**Comment by jh3y** [comment]
Hey @NameFILIP 👋 
Not sure if this is something we would put into the core styling. It's a little subjective in approach. You might extend the `width` of the `Toast`. Alternatively you may choose to use `word-break` or `overflow` to improve the UX.

For example, this would solve the UX problem if you wanted to maintain equal `width` toasts.
```
class ToasterExample extends React.Component {
  add = () => {
    toaster.info(
      "SomeReallyLongWordWithNoSpaces",
      {
        autoHideDuration: 5000,
        overrides: {
          Body: {
            style: {
              wordBreak: "break-all"
            }
          }
        }
      }
    );
  };
  render() {
    return <Button onClick={this.add}>Info toast</Button>;
  }
}
```
But alternatively you may not want the `word-break` and go with
```
class ToasterExample extends React.Component {
  add = () => {
    toaster.info(
      "SomeReallyLongWordWithNoSpaces",
      {
        autoHideDuration: 5000,
        overrides: {
          Body: {
            style: {
              width: 'auto'
            }
          }
        }
      }
    );
  };
  render() {
    return <Button onClick={this.add}>Info toast</Button>;
  }
}
```
And of course the other scenario being that your text doesn't overflow at all 😄

**Comment by NameFILIP** [comment]
@jh3y Do you think when content goes out of the Toast is a better UX than allowing to scroll?
I know I can leverage overrides to customize it, but shouldn't the default behavior handle such a common use-case?

**Comment by jh3y** [comment]
@NameFILIP No. I completely agree it's not great UX for there to be overflowing content in your `Toast`. Yet, it also wouldn't be great UX to have the `Toast` container be scrollable.

It isn't a common use case to show large unbroken strings in a `Toast`. Displaying a stack trace or similar in the `Toast` might not be ideal. It would be common to have something like a small message about an Error accompanied by a link to a log etc. Or even cutting the content off with ellipsis. A `Toast` displays small quick digestible notifications. Consider a CI dashboard. If the build fails, you are likely to see a `Toast` saying "Build Failed". Yet, you need to dig deeper to see why.

After discussing this offline, `width: auto` or `word-break: break-all` would be the better solution. The former might break the visual flow if you have stacking `Toast` of inconsistent width. These aren't changes we will make though.

**Comment by houmark** [comment]
@jh3y I'm trying to just make my toast a bit wider than normal, because I have it positioned in the top/center but no matter what overrides I put, it stays around the same width as with no override.

Can it be that `width: auto` is just not being applied? Ideally, I would like to keep a slightly longer text on one line if the browser width allows it but no matter what I do, it stays the same width.

Here's a CodeSandbox with the override applied, but it does not seem to do anything to the width:
https://codesandbox.io/s/toaster-basic-usage-cfu31
