### ISSUE TITLE
[StatefulInput] Enter on password input field unmasks password

### ISSUE THREAD

**Issue by aitchiss** [uber-web/baseui#1662]
## Current Behavior

Using a StatefulInput with type 'password' as the last element in a form results in the password becoming visible when the user hits enter in the input field, so what you see is:

- Password unmasks
- Form submits

Similarly, hitting the enter key when the focus is on the mask/unmask button results in the form submitting, when it should only mask/unmask the input.

You can reproduce with:

```
<form>
  <StatefulInput type="password" />
</form>
```

## Expected Behavior

- Hitting enter on the input field should have no impact on the password being masked/unmasked
- Only hitting enter key while focused on the mask/unmask button should toggle password masking on and off
- Hitting enter while focused on the mask/unmask button should not trigger the default input field enter key behaviour (i.e. submitting a form when in a form)

**Comment by houmark** [comment]
I'm seeing the same behavior and this is a pretty bad bug that I'm wondering how it made it in? Users privacy and overall security are being affected as the password is easily visible for 2-5 seconds when submitting a form (if someone is watching over your shoulder when logging in), depending on how long time for example login verification takes.

**Comment by gergelyke** [comment]
Reproducing codesandbox: https://codesandbox.io/s/input-for-passwords-bc94h

**Comment by gergelyke** [comment]
thanks @aitchiss @houmark - this was fixed and released in 8.13.0
