### ISSUE TITLE
Invalid DOM nesting warnings in Modal

### ISSUE THREAD

**Issue by schnerd** [uber-web/baseui#1691]
## Current Behavior

As a result of #1627, the modal component will now emit numerous warnings about invalid dom nesting if you end up using a block-level tag like `<div>` inside of a ModalBody:

![image](https://user-images.githubusercontent.com/875591/62403989-ed4b0b80-b545-11e9-9fc9-cd12e46df082.png)

The Modal probably shouldn't make too many assumptions about what the consumer will put in ModalBody, or maybe users should have to opt-in to using `<p>` tags for Modal, especially considering modal content usually isn't indexed in search engines and thus shouldn't be much of an SEO concern.

## Expected Behavior

Valid DOM nesting by default.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.12.0  |
| browser | Chrome       |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by houmark** [comment]
I agree with @schnerd on a less opinionated approach on this. I know that these breaking changes were done with the purpose of improving SEO out of the box, but I would have liked to see more sensible defaults. `$as="div"` is in pretty much every modal and I had to fix that when updating to avoid errors. For us, almost all modals have some kind of UI and not just a text, so expecting content use a `p` as wrapper is for me a bit too opinionated.

In the end it's up to the developer to ensure all parts of a site is SEO optimized and Baseweb should of course do its part, but also not so aggressively that it makes using for example modals more complicated in most use cases.

**Comment by gergelyke** [comment]
That makes sense - I'll roll this back first thing Monday morning

**Comment by houmark** [comment]
Thanks a lot for listening to the feedback, and the development pace you guys are putting in is really great — it's hard to keep up with even updating to the latest version :)

**Comment by tajo** [comment]
#1694 reverts it

**Comment by pencilcheck** [comment]
Getting the same issue when using PhoneInput here: https://github.com/uber/baseweb/issues/5273
