### ISSUE TITLE
Select UX review changes

### ISSUE THREAD

**Issue by schnerd** [uber-web/baseui#171]
Some of the changes that we discussed while reviewing the new Select component.

**Styles**
- [x] Select element has `not-allowed` cursor even though not disabled, should have default cursor
- [x] Center search dropdown (currently alligned left)
- [x] Selected option in single-select looks very dim, should be black
- [x] Tag styles/padding (@nguyensomniac to update the designs)
- [x] Active single select should maybe have border/highlight (@nguyensomniac to update designs)
- [x] Select & highlighted items should have different styles (@nguyensomniac to update designs)
- [x] Make sure disabled state works as per  https://github.com/uber-web/baseui/pull/198

**Keyboard**
- [x] Single-select should have tabindex so it can be focused (multi-select is okay since it has input)
- [x] When `TYPE.select` is focused, down arrow and spacebar should open dropdown
- [x] Backspace should delete an item in multi-select
- [x] Pressing enter on highlighted item should select/deselect it. 
- [x] Escape should close the dropdown for both single and multi-select

**General Functionality (some reported by users)** (Added by @abmai)
- [x] Dropdown begins in an open state
- [x] For `TYPE.search` dropdown does not re-open after closing
- [x] Selecting an object should return entire object not just `id` and `label`
- [ ] For `TYPE.search` selecting an option does not clear current input value
- [ ] Single-mode `TYPE.search` not supported? We should have something similar to default behavior of react-select Single mode

**Stories**
- [x] Search doesn't seem to work reliably in the first multi-select storybook example. Maybe we should do a fixed set of options in first story, and have a separate story for demonstrating async results?
- [x] Images and labels are overflowing tag in [custom label story](https://baseui.netlify.com/?selectedKind=Select&selectedStory=In%20Select%20multiple%20mode%20with%20Custom%20Labels%20and%20Custom%20Selected%20labels&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
- [ ] Clear the search term on item selected or dropdown closed, make the closing configurable
- [ ] Add a search/single mode example

**Comment by blackswanny** [comment]
https://github.com/uber-web/baseui/pull/221

**Comment by schnerd** [comment]
Also it seems like the click target should be the whole highlighted row, not just the text:

![kapture 2018-09-11 at 15 09 50](https://user-images.githubusercontent.com/875591/45390658-f4d39000-b5d4-11e8-9796-6c825ff207e2.gif)

Is this an issue with Select or Menu? 

cc @abmai

**Comment by abmai** [comment]
> Also it seems like the click target should be the whole highlighted row, not just the text:
> 
> ![kapture 2018-09-11 at 15 09 50](https://user-images.githubusercontent.com/875591/45390658-f4d39000-b5d4-11e8-9796-6c825ff207e2.gif)
> 
> Is this an issue with Select or Menu?
> 
> cc @abmai

Seems to be an issue in `Select` atm because the `onClick` handler is attached to the custom label component.

**Comment by JoshRosenstein** [comment]
was just about to create an issue but just saw @schnerd comment. Along with the click target bug, the Select Icon is off. in storybook, the "Show Info" button is hiding the the issue.

![select_Issue](https://user-images.githubusercontent.com/32781407/45766593-f705a200-bc05-11e8-91fe-5fbcbd730254.gif)

**Comment by blackswanny** [comment]
@schnerd  click is fixed
@JoshRosenstein arrow is fixed

**Comment by schnerd** [comment]
Oleg and I just discussed some further changes over Zoom, adding them here:

- [ ] 
- [ ] 
- [ ]

**Comment by schnerd** [comment]
Oleg and I just discussed some further changes over Zoom, adding them here:

- [ ] Currently `props.onChange` is called for both _selected value_ change and _text input value_ change. We should refactor so that `onChange` is only called when _selected value_ changes, and we create another `onTextInputChange` for changes to the _text input_ value
- [ ] Rather than having `onTextInputChange` return a promise that says when options have finished loading, we should just overload the `options` prop to be `Option[] | () => Promise<Option[]>`. This is more flexible as we can call the async options function when the dropdown is focused but still empty to get the initial list of options, as well as when the text input value changes.

**Comment by schnerd** [comment]
@abmai @nadiia ^ let us know if you have feedback on that
