### ISSUE TITLE
Component page on doc site should link to the component's type definition file

### ISSUE THREAD

**Issue by chasestarr** [uber-web/baseui#1726]
Type definitions on the documentation site are mechanically generated and _do not spark joy_. Developers often need to open up a component's type file anyway to better read it. It may be useful to directly link to the source in addition to displaying the types in the website.

**Comment by shannonmoeller** [comment]
Not sure how hard it would be, but it would be awesome if the type in the docs linked to the specific line in the source where the type is defined. Clicking `union` here for example:

![image](https://user-images.githubusercontent.com/155164/62715998-be59ed00-b9be-11e9-8b21-0403225b8861.png)
