### ISSUE TITLE
Formik Interop

### ISSUE THREAD

**Issue by jaredpalmer** [uber-web/baseui#1754]
I noticed [in the roadmap](https://baseweb.design/getting-started/roadmap/) that Formik support is on deck. Would be happy to assist.

**Comment by gergelyke** [comment]
Hi @jaredpalmer - thanks for offering help! Probably the documentation site's wording is misleading, in that table we wanted to list things that we decided not to include in Base Web. I am sorry for the confusion and I am going to update the wording.
