### ISSUE TITLE
How to have two Toast's on the same page/component in two different locations?

### ISSUE THREAD

**Issue by houmark** [uber-web/baseui#1769]
## Current Behavior

I have a UI where I would like to have a confirmation toast in the lower right side and an "information" toast which would be in the top center.

How can I add two toasts within the same component, and then programmatically address each one of them individually?

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.16.4  |
| React   |     16.8.6    |
| browser |    Chrome 76.x     |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hi @houmark - from a strictly UX point of view, probably notification should always pop up from the same spot, no matter if they are confirmation or information

with that said, I am not sure how to achieve that - Nadiia, can you help with this? is it possible with the current setup?

**Comment by houmark** [comment]
I somewhat agree and disagree :) Notifications in relation to user interaction is always the same place, but notifications from third party changes (less important to notice) can go on a different location for me without being confusing.

**Comment by houmark** [comment]
Awaiting response on this one, but I think this needs new development to be possible.

**Comment by gergelyke** [comment]
> Awaiting response on this one, but I think this needs new development to be possible.

Hi @houmark - this is not something the core team can take on, as our internal design always use one Toast only. If you have the bandwidth to contribute, we can potentially land it :)

**Comment by houmark** [comment]
Understood, but can we then set the proper labels and remove stale so it isn't forgotten?

**Comment by gergelyke** [comment]
done :)

**Comment by chasestarr** [comment]
I helped someone figure this out the other day, sharing here: https://codesandbox.io/s/toaster-basic-usage-4rqld

closing, let me know if this does not work for you

**Comment by houmark** [comment]
Nice! That's great and simple. I had thoughts in that direction actually but didn't get around to try it out.

**Comment by houmark** [comment]
Maybe this should be added to Toast docs for anyone else to know how this can be done.

**Comment by gergelyke** [comment]
@houmark can you please open a PR adding this as an example?
