### ISSUE TITLE
[Select] Cursor inserted at beginning instead of end of value

### ISSUE THREAD

**Issue by kylegach** [uber-web/baseui#1794]
## Current Behavior

Sandbox: https://codesandbox.io/s/ndonk?module=/example.tsx

1. Select an option
1. Click into the Select
1. Notice the text cursor is inserted at the beginning of the value

> I understand that this behavior may be intentional, as it allows the user to "just start typing" to choose a new value. That conflicts with the behavior of a standard text input, though, so I would encourage a different approach.

## Expected Behavior

1. Select an option
1. Click into the Select
1. The text cursor is inserted at the end of the value

> If you agree this is an issue and can provide some guidance on where to get started, I'm happy to try my hand at a fix.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v8.16.5  |
| React   | 16.8.6  |
| browser | Mac Chrome, Mac Firefox, (all?) |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by Patil2099** [comment]
@gergelyke Can I work on this issue?

**Comment by kimasenbeck** [comment]
@Patil2099 are you still looking into this issue?
