### ISSUE TITLE
[RFC] Internationalization Strategy

### ISSUE THREAD

**Issue by schnerd** [uber-web/baseui#183]
The topic of customizing labels for internationalization came up in #178, and it seemed like we haven't really discussed internationalization/rtl too much.

Regarding _translations_ specifically, here are some of the approaches other folks are using:

- **Atlaskit** supports an `i18n` object prop on components to override labels ([Example](https://atlaskit.atlassian.com/packages/core/pagination)). This seems less desirable as you'd need to override the strings again every time you use the component, unless a wrapper is created.
- **Blueprint** has a similar approach of allowing you to override strings through props ([Example](https://blueprintjs.com/docs/#core/typography.right-to-left-text))
- **Antd** has a json file with translated strings that you set up at the top of your app through a `<LocaleProvider locale={frJsonObject} />` ([Example](https://ant.design/docs/react/i18n)). This approach is kind of nice because translation can be a one-step process that applies to all baseui components, rather than overriding at call-sites. We could also pass through number formatting and date formatting concerns into this provider to be used throughout the app.

It seems like we should move forward with the antd approach.

I'm personally less familiar with what's required for rtl support, so it would be good to get someone more experienced in that area to chime in, but looking at [material](https://material-ui.com/guides/right-to-left/) or [blueprint](https://blueprintjs.com/docs/#core/typography.right-to-left-text) could yield some insights.

**Comment by schnerd** [comment]
And to be clear about where translated strings may be needed...

Datpicker has quite a few static labels:
<img src="https://user-images.githubusercontent.com/875591/45053306-7314bd00-b03e-11e8-9c73-b03b8efd69e6.png" width="300" />

Select/Input has the default input and and "No Results"
<img src="https://user-images.githubusercontent.com/875591/45053413-c2f38400-b03e-11e8-8854-6f7e7702e62a.png" width="300" />

Pagination has "Prev" and Next"
<img src="https://user-images.githubusercontent.com/875591/45053434-d69eea80-b03e-11e8-9ddb-bde19cf647cc.png" width="300" />

There are also likely going to be hidden / a11y labels. For example, the close button on the modal:
<img src="https://user-images.githubusercontent.com/875591/45053591-41e8bc80-b03f-11e8-98d9-7a4246aa8354.png" width="500" />

And there are probably plenty more that I'm missing.

**Comment by MarkReeder** [comment]
My preference would be to handle text strings/i18n concerns as we handle themes. If we go that route, we'd probably want some tooling around scoping/merging/extracting of individual component string sets so that you wouldn't have to import all the strings for the entire suite of components to use a single component. That could also be something we punt until later if there are only a handful of strings across the entire project.

**Comment by gergelyke** [comment]
this is currently in progress https://github.com/uber-web/baseui/pull/951
