### ISSUE TITLE
[Table Sort] Fails to sort when user clicks on negative space in column header

### ISSUE THREAD

**Issue by kimasenbeck** [uber-web/baseui#1830]
Issue: Columns can only be sorted by clicking on the text within column header. 
Expected: should be able to sort column by clicking anywhere within header (including negative space, not just on text) Clicking on the text is counterintuitive, and may lead to many users failing to discover sorting functionality. 

For an example, play around with table header on [this page](https://baseweb.design/components/table/#table-with-sorting-by-a-column): Try clicking on the area where the arrow is pointing
![image](https://user-images.githubusercontent.com/10892241/64211168-2d115580-ce5a-11e9-80bd-e7d896ea5b4c.png)

**Comment by chasestarr** [comment]
Considered this when first building the component and chose to implement similar to [material design](https://material-ui.com/components/tables/#sorting-amp-selecting). I suppose there are different opinions on what's a preferable UX 🤷‍♂ Happy to accept a PR with an additional configuration that allows for the whole cell to be clicked (needs to ensure it works with sort + filter).

**Comment by rohit012** [comment]
For sort use case we can pass extra config to SortableHeadCell component and based on that we set listeners and cursor css attribute on HeadCell or SortableLabel.

Filtering seems complicated. In case of filtering, we have a separate Filter component which accepts filter function and is inside StyledHeadCell component. So applying filter function and css cursor property on StyledHeadCell doesn't seem straightforward.

Should we create a new component FilterHeadCell similar to SortableHeadCell which can handle this use case properly. May be I am missing something. Any suggestion @chasestarr

**Comment by chasestarr** [comment]
here is an example of combining the two https://codesandbox.io/s/table-with-column-filtering-d2ldk no need for a new sort header component

**Comment by chasestarr** [comment]
I've prototyped something similar here https://github.com/uber-web/baseui/blob/master/src/data-table/header-cell.js#L93-L100 for a more feature-rich data table (fyi not ready for general use)

**Comment by rohit012** [comment]
@chasestarr thanks for clarification. Pls let me know what you think about the PR.

**Comment by chasestarr** [comment]
Thank you @rohit012 for contributing this change, and thank you to @kimasenbeck for bringing up the opportunity for improvement
