### ISSUE TITLE
[Tab] Support mouse events

### ISSUE THREAD

**Issue by lczhao** [uber-web/baseui#1831]
## Feature description
Currently there is no mouse event API for Tab. so making a tooltip pops up when user hover a tab is impossible.
even if I wrap `Tab` around `Tooltip` or `Popover` doesn't do it. (since `Tabs` checks immediate child `=== Tab` I think?)

an Ideal scenario would be:

```js
<Tabs>
  <Tab onMouseEnter={myMouseEnter} onHover={myHover}>My Tab</Tab>
</Tab>
```

**Comment by chasestarr** [comment]
I'm not exactly sure what you want to achieve, but here are some possible examples: https://codesandbox.io/s/controlled-tabs-usage-3uo57
