### ISSUE TITLE
[Bug] withStyleDeep errors on non StyledComponents

### ISSUE THREAD

**Issue by abmai** [uber-web/baseui#184]
The change introduced in https://github.com/uber-web/baseui/pull/162 created an error scenario where if the user is trying to style a non-StyledComponents component, the app will error out.

The following use case will error out

```js
import {styled} from 'baseui';

const BaseComponent = ({props}) => <div {...props} />;
const StyledBase = styled(BaseComponent, ...);
```

We will try to apply `withStyleDeep` on `BaseComponent`, but `withStyleDeep` expects a `StyledComponent`. `withStyleDeep` does not cover the same surface as `styled` (probably could have pointed that out from looking at the types in https://github.com/styletron/styletron/tree/master/packages/styletron-react).

Possible fixes here include:

* Revert to calling `baseStyled` before calling `withStyleDeep` - this requires us to change up our API a bit here, going from accepting `(...args)` to explicitly asking for `(element, style)`. We do manual merging of styles - a bit more gnarly here but works?

```js
export default function styledWrapper(element: any, style: any) {
  // Also allow passing deep style overrides via $style prop
  // Ex: <StyledDiv $style={{color: 'red'}} />
  // Issue for supporting this natively in styletron:
  // https://github.com/rtsao/styletron/issues/221
  return withStyleDeep(baseStyled(element), (props: {$style?: ?{}}) => {
    const {$style} = props;
    let finalStyle;
    if (typeof style === 'function') {
      finalStyle = style(props);
    } else {
      finalStyle = style;
    }
    if (typeof $style === 'function') {
      return {
        ...finalStyle,
        ...$style(props),
      };
    }
    return {
      ...finalStyle,
      ...$style,
    };
  });
}
```

* Reach into `styletron`, ensure that the component *is* a StyledComponent, looks like we can check for the existence of `__STYLETRON__` on the object: https://github.com/styletron/styletron/blob/master/packages/styletron-react-core/src/index.js#L543 - also used here: https://github.com/styletron/styletron/blob/master/packages/styletron-react-core/src/index.js#L165

```js
export default function styledWrapper(...args: any) {
  // If user is trying to style a styled component
  // use withStyleDeep, otherwise use baseStyled
  let styleFn = baseStyled;
  if (args[0] && args[0].__STYLETRON__) {
    styleFn = withStyleDeep;
  }
  // Also allow passing deep style overrides via $style prop
  // Ex: <StyledDiv $style={{color: 'red'}} />
  // Issue for supporting this natively in styletron:
  // https://github.com/rtsao/styletron/issues/221
  return withStyleDeep(styleFn(...args), (props: {$style?: ?{}}) => {
    const {$style} = props;
    if (typeof $style === 'function') {
      return $style(props);
    }
    return $style || {};
  });
}
```

Thoughts?

**Comment by schnerd** [comment]
Hmm neither of them are beautiful. For some reason the second one seems conceptually simpler to me–the use of `__STYLETRON__` isn't ideal but i'd be surprised if that changed, we could always add a unit test to make sure it's present on styled components so a styletron version bump doesn't bite us.

It's also interesting to think about what this will look like if we get Ryan to implement the "middleware" that allows us to move the `$style` concern elsewhere. In that case, your first suggested approach would become:

```js
export default function styledWrapper(element: any, style: any) {
  return withStyleDeep(baseStyled(element), style);
}
```

Second approach would become:

```js
export default function styledWrapper(...args: any) {
  let styleFn = args[0] && args[0].__STYLETRON__ ? withStyleDeep : baseStyled;
  return styleFn(...args);
}
```

I'm not 100% sure how styletron's internals work, but it seems like the former would also add extra HOC overhead to the rendering chain. Maybe we can go with the `__STYLETRON__` appraoch and then ask Ryan's advice when he's back from vacation?

**Comment by abmai** [comment]
Yep also agree that `__STYLETRON__` is much cleaner for now. I'll go ahead and do that. Thanks!
