### ISSUE TITLE
[Button] Pill shape doesn't work

### ISSUE THREAD

**Issue by jasonbarone** [uber-web/baseui#1885]
## Current Behavior

The pill shape does not work in base ui 9.0.0. Codesandbox here: https://codesandbox.io/s/basic-usage-mvw32

## Expected Behavior
"pill" shape string or type should trigger pill shape style.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.0.0  |
| React   |  16.9.0       |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hi Jason! it's being released right now under 9.1.0
