### ISSUE TITLE
Flow error: An index signature declaring the expected key / value type is missing in object literal

### ISSUE THREAD

**Issue by NameFILIP** [uber-web/baseui#1910]
Flowtype complains about passing a variable of type `TagKindT` to the `kind` property of the `Tag` component.

See the [example](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecYCeYScAchACYkC+cAZlBCHAORSoYsBQXSAHpFhw0EAHYBneAGkAkqQAicALxwA2lzitRSAK4woKADYtMG1mCigUUAibMtI44DGAA3JHc0sA7tdHBRAHNPLSRAlBd3EJY0HUkmOwBdADp2Ch00JAAKLIBrAIoAWRQwbFykAgBKZQA+XDN80SKS1XKCROU4NoBuM3YYHShRLoLisF7qbBxqSt6uEQl4ABUUQKkCzoB5ACMAKyQMZIYkJAAvbNkFWa5CYjgVtYKlzoASKQrxAB5bpAg6e9W6yaNTmPwBgQACowwOJOjgAD4NAoAfgAXOCgRQlqZNGgABbAQwUdiidHkKhceHUOZ0HSiDDAMTguBZCwQGHoh5Q9niao4PpIAZDOCfChuOAAejqXGoPDB3JhcMRmkaFDRGKepipc34gngVDoKB0hngtPpLiZABkUEEdKskA9WdDxOiFbz6rixJJcCMmnBaCo2TDepp+oNhlkzJpPg8o5pfRQlDhVbL43AanHNABRIKGYDiPFxz4Sh4ZzTXWVAA).

**Comment by gergelyke** [comment]
@NameFILIP can you please provide what version of Base Web you are on? Also, an example using base imports?

**Comment by NameFILIP** [comment]
I'm using `8.10.0`. Yes, I copied the type definitions in the example from the node_modules files

**Comment by chasestarr** [comment]
Seems to be related to the way that `KINDS` is built. Switching from an array + reduce to an explicit object removes errors. [try-flow](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecYCeYScAchACYkC+cAZlBCHAORSoYsBQXSAHpFhw0EAHYBneAGkAkqQAicALy4ucOKKQBXGFBQAbAFytNOvfpaY1cMFFAooBYy1v3HLOF2o8RE+ABUUAHMpYFEKZTgAeQAjACskDAA6BiQkAC8kAApZBQBKAG4uQmI4QJCwin9IgBIpJAJxAB4SpAg6MuDQ8IA+IuKiEnKABUYwcUicAB9rAGtKgH5jcu6qq3U0AAtgfQp2UWNyKi4p6n66LVEMYDFOoLgs2whx5eDR5-E81XV2GC0oURwJoUYAANzgAHoep5vANSu9xpMZup5uElndVv4rKd+vxBPAqHQUFp9PALlcYDdAQAZFCiIJaYJIcqPMbiYwIz7fYRiSS4OCoiK0FRPcZFH5IP4Ah7WdRNcqy9QCypKHCC7xKuA9RXqACi9P0wHEm0VTQh5W16kKXi4QA)

**Comment by chasestarr** [comment]
Thanks for reporting!
