### ISSUE TITLE
Types of some event props are not correct

### ISSUE THREAD

**Issue by choyongjoon** [uber-web/baseui#1915]
Types of some event props are not correct. So It makes TS error.

## Current Behavior

For example, the `onClick` prop of `Button`:

https://github.com/uber-web/baseui/blob/b6d360058ee827041d75c8f407822f4d579a571b/src/button/index.d.ts#L47

## Expected Behavior

It should be
```ts
onClick?: (event: React.MouseEvent<HTMLButtonElement>) => any; 
```

or

```ts
onClick?: React.MouseEventHandler<HTMLButtonElement>; 
```
## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.0.0  |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by choyongjoon** [comment]
You can search all cases (in all `index.d.ts` files) through this regex:
```regex
event: React\.(.*)EventHandler
```
and replace with this regex:
```regex
event: React.$1Event
```

**Comment by gergelyke** [comment]
thanks for opening the issue @choyongjoon ! would you mind sending a PR fixing it?

**Comment by choyongjoon** [comment]
Ok. I sent a PR.

**Comment by gergelyke** [comment]
Thank you, we'll review later today!
