### ISSUE TITLE
Datepicker in popover breaks as it doesn't return consistent value

### ISSUE THREAD

**Issue by matchatype** [uber-web/baseui#1916]
Datepicker returns a date object if you focus on the input and then click on any date. However, if you start typing, the date object returns wrapped inside an array.

From then on, the Datepicker component is broken and you are not able to select and click on a date anymore.

I thought `range={false}` would fix it, but in my experience it doesn't.

![Screen Capture on 2019-09-18 at 13-23-48](https://user-images.githubusercontent.com/28128/65144541-df7b1800-da17-11e9-93cb-6ecea8be279f.gif)

https://codesandbox.io/s/9qbfd?module=/example.js

## Current Behavior
Selecting a date by clicking returns a date.
Typing a date returns a date wrapped in an array.
After typing, the calendar picker is broken and can't select a date by clicking on it anymore.

## Expected Behavior
Selecting a date by clicking should return a date.
Typing a date should return a date.
After typing, the calendar picker should allow me to click on a date and return a date.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.3.1  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
The fixed was released in 9.3.2 - please let us know if you run into further issues!
