### ISSUE TITLE
Datepicker no longer respects placeholder or formats correctly as of v8.18.0

### ISSUE THREAD

**Issue by aitchiss** [uber-web/baseui#1917]
As of the update to v8.18.0, Datepicker no longer seems to respect placeholder props, and formatting of selected date appears to be broken.

## Current Behavior

See reproducing codesandbox here: https://codesandbox.io/embed/datepicker-in-a-popover-f258c

Notice that:
- Placeholder for date is always YYYY/MM/DD regardless of prop
- Formatting to UK date string "dd/MM/yyyy" results in output e.g. 0809/20/19 instead of 08/09/2019

## Expected Behavior

- Placeholder given in props should be displayed
- dd/MM/yyyy should yield e.g. 08/09/2019

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | 8.18.0 |
| React   |     16.9.0    |
| browser |   Chrome      |

I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
Hi @aitchiss - thank for opening this issue! It was a regression introduced in the 8.x release, and fixed in 9.x. As we are not backporting any fixes, please upgrade to the latest version. If for some reason you cannot do that, I'd recommend using an earlier Base Web version.
