### ISSUE TITLE
Wrapping Tab into React.FC prevents tab switching

### ISSUE THREAD

**Issue by simPod** [uber-web/baseui#1948]
I might be doing it wrong but I tried to wrap `Tab` into another component as

```ts
import {Tab as BaseUITab, TabProps } from 'baseui/tabs';

const Tab: React.FC<TabProps> = ({ children }, props) => (
  <BaseUITab overrides={{ Tab: { style: { flex: 1 } } }} {...props}>
    {children}
  </BaseUITab>
);
```

However, when this is used within `<StatefulTabs>` tab switching stops working.

Example https://codesandbox.io/s/uncontrolled-tabs-usage-3e5y2 There are two usage types, first is my wrap attempt, second is typical documented approach to show it works just fine that way.

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.4.2  |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
hi @simPod 

this is not a supperted use-case - if you want to make sure this approach works, you have to look under the hood of the tabs component and implement the layer that connects the Tab components to the parent Tab

**Comment by gergelyke** [comment]
What do you want to achieve?

**Comment by simPod** [comment]
Thanks for reply, got it.

I just wanted to simplify sharing of common attributes like `overrides`. Now I refactored it to having ` const commonTabProps = { overrides: {...}, ... }` and constructing tabs as `<Tab {...commonTabProps}`

**Comment by chasestarr** [comment]
Seems like the issue is resolved. Let me know if it should be re-opened

**Comment by simPod** [comment]
@chasestarr I'd still love to do it. `<Tab {...commonTabProps}` is only a workaround

See https://codesandbox.io/s/baseweb-nklju?file=/src/example.tsx

**Comment by simPod** [comment]
I have created more relevant followup here https://github.com/uber/baseweb/issues/3548
