### ISSUE TITLE
Allow a list of string/number/boolean values to be passed as select options

### ISSUE THREAD

**Issue by Firenze11** [uber-web/baseui#1954]
##  Feature description

Right now `options` is only limited to list of objects:
`options nullable $ReadOnlyArray<$ReadOnly<object>> = []`
Would be valuable to allow directly passing list of strings or numbers to it, to prevent having to converting string/number representation back to objects during usage.

**Comment by gergelyke** [comment]
@Firenze11 I'd like to ask you to consolidate your feedback into this issue, that we've opened to discuss Select improvements: https://github.com/uber-web/baseui/issues/1821
