### ISSUE TITLE
z-index of select options is not as high as slider knob

### ISSUE THREAD

**Issue by Firenze11** [uber-web/baseui#1956]
## Current Behavior

z-index of select options is not as high as slider knob, which causes weird effect when the select option is open and overlays on the slider.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.4.2 |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@Firenze11 can I ask you to create a codesandbox that reproduces this issue please?

**Comment by nadiia** [comment]
Added a fix here https://github.com/tajo/react-range/pull/39

**Comment by nadiia** [comment]
`react-range@1.4.1` with a fix is published

**Comment by Firenze11** [comment]
That's so fast!! Thank you!
