### ISSUE TITLE
Figma (or Sketch) File for Base Web

### ISSUE THREAD

**Issue by notbrett** [uber-web/baseui#1964]
## Feature description

Having a Figma (or Sketch) file with all the Base Web stuff in it would allow for quick composition by a Design team. It would also increase collaboration and facilitate better “everyone on the same page” conversations among Engineering and Product. It really helps to be able to show a component in Figma and have it be visually identical (or similar enough) that Engineering has confidence of which component is being targeted.

This is a big win for teams using Base Web as a visual default to build out internal applications that are all about functionality (branding, visual design not the priority).

**Comment by gergelyke** [comment]
Hi @notbrett - if you are using Framer, there is already a Base Web library published. Would that work?

**Comment by notbrett** [comment]
Oh cool! Alas, I tried Framer X when it first came out. Thus, I can’t check out the library without buying a subscription. (This is the big win for Figma as it has a great free tier.) Thanks for info!
