### ISSUE TITLE
FileUploader - The 'ComponentMessage' override gets rendered twice.

### ISSUE THREAD

**Issue by amandeep224** [uber-web/baseui#1981]
When a component is passed as a ComponentMessage overrides in overrides prop to the FileUploader component, it gets rendered twice. 

Code Sandbox link:
[https://codesandbox.io/s/file-uploader-basic-usage-f855b](url)

(See the example.js file)

**Comment by gergelyke** [comment]
hi @amandeep224 - it happens, because we use that wrapper for two messages: https://github.com/uber-web/baseui/blob/master/src/file-uploader/file-uploader.js#L98-L109

if you want to change the text, please refer to https://baseweb.design/guides/internationalization/
