### ISSUE TITLE
Datepicker exclusion doesn't look right 

### ISSUE THREAD

**Issue by kahwee** [uber-web/baseui#1994]
##  Current Behavior

Date exclusion always to leave the first and the last day looking enabled. Looks like a styling issue

Using filterDate with a function to return false doesn't disable the the month back and forward navigator. (I understand why this is tricky but the docs could point out the differences more)

Also clicking on the month selector when includeDates is set to today yields a full month list even though the month back and forward navigator is disabled

## Expected Behavior

Date exclusion should not mark first and last day of month as black. It looks like it is enabled.

Excluding dates should consider the month selector and navigator.

## Your Environment

Test it out here -- https://codesandbox.io/s/datepicker-23wcr

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.6.1  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
@kahwee any chance you could help us with fixing it?

**Comment by kahwee** [comment]
I was hoping your team can get to it soon. ;)

Gotta finish our P0s first and I can dig deeper.

If anyone is free to take this up, please go ahead first.

Thanks!
