### ISSUE TITLE
[Button] Improvement TODOs

### ISSUE THREAD

**Issue by abmai** [uber-web/baseui#207]
* [x] A11Y Check-thru
  * [x] Focus style if we do `outline: none`?
  - read: https://jmperezperez.com/outline-focus-ring-a11y/
  - read: https://a11yproject.com/posts/never-remove-css-outlines/
* [x] Design Review
  * [x] Spacing / padding
* [x] Special kind for `spinner`
* [x] justify items `center` and not `space-between` by default

**Comment by JoshRosenstein** [comment]
Hey there, I was just pokin around and was wondering if there was a reason Button has justifyContent space-between and not centered? This may result in undesired style for for full width Buttons if both enhancers are not supplied.

Example:
[![Edit uber_centerBTN](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w0wzxvp608?view=preview)

**Comment by abmai** [comment]
> Hey there, I was just pokin around and was wondering if there was a reason Button has justifyContent space-between and not centered? This may result in undesired style for for full width Buttons if both enhancers are not supplied.
> 
> Example:
> [![Edit uber_centerBTN](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/w0wzxvp608?view=preview)

I think this was originally intended to create the "flushing" behavior for enhancers. I agree that we should follow native behavior and use `center` here; we can flush the enhancers separately or leave that up to the users.

Will PR up a fix. Thanks for pointing this out!
