### ISSUE TITLE
[Proposal] Consolidate all override usages to using `getOverrideObject`

### ISSUE THREAD

**Issue by abmai** [uber-web/baseui#208]
Replace all instances where we use `getOverride` + `getOverrideProps` with `getOverrideObject`. I added the latter helper with the most recent `Menu` changes and looks like we would always want to pass-thru component + props + style overrides together anyway?

Example code snippet:

```js
export default function OptionList({
  item,
  getItemLabel = (item: *) => (item ? item.label : ''),
  overrides = {},
  ...restProps
}: OptionListPropsT) {
  const {component: ListItem, props: listItemProps} = getOverrideObject(
    overrides.ListItem,
    StyledListItem,
  );
  return (
    <ListItem {...restProps} {...listItemProps}>
      {getItemLabel(item)}
    </ListItem>
  );
}
```

**Pros**
* Consolidate everything into 1 function call
* Less chances of forgetting to do props overriding

**Cons**
* Callsite of `getOverrideObject` can be long

Thoughts? cc @nadiia @schnerd @blackswanny

**Comment by blackswanny** [comment]
ok, good idea

**Comment by chasestarr** [comment]
somewhat related - i've been using [this pattern](https://github.com/uber-web/baseui/blob/master/src/file-uploader/file-uploader.js#L34-L58) in components. feels like it cleans up the render function a bit by reducing the override props spreading

**Comment by schnerd** [comment]
> somewhat related - i've been using [this pattern](https://github.com/uber-web/baseui/blob/master/src/file-uploader/file-uploader.js#L34-L58) in components. feels like it cleans up the render function a bit by reducing the override props spreading

One thing to be wary of is that your logic is creating new react components on every single render. I'm pretty sure this could cause the same bug [encountered here](**url**) with inlined override functions – where focus or other state may not be maintained properly.

That said, wiring up the override logic can certainly feel repetitive/cumbersome, I share your desire to somehow simplify it. A custom babel transform might be one option, but that obviously has its own trade-offs. Happy to discuss idea further.

**Comment by chasestarr** [comment]
good point - i just got bit by that override bug yesterday after i posted that comment
