### ISSUE TITLE
[Proposal] Use system font stack for Base UI

### ISSUE THREAD

**Issue by nguyensomniac** [uber-web/baseui#226]
Design is revisiting the type for the internal version of Base UI, and as part of that we'd like to take a stronger opinion on a typeface for the open-source version, i.e. using the system font stack instead of Helvetica.

Looking at what the new type looks like compared to various other typefaces (San Francisco, Helvetica) you can see, the new font for body text is proportionally similar to San Francisco, which would help make the open-source and non-open-source versions look more consistent, at least on Macs. And, as a plus, it would help make re-creating layouts much easier :)

Would love to hear some thoughts—we're still in the early stages of all of this.

**Comment by alex-page** [comment]
We implemented system fonts across our design system ( https://github.com/govau/uikit ) to great success. For our team the main reasons were to reduce total download size for users in remote locations.

I have also heard good things from designers using system fonts. They have a consistent x-height across all systems which makes it possible to align the different families to a grid in a consistent way.
