### ISSUE TITLE
[Input Component] Stateless Input should be fully-uncontrolled by default(?)

### ISSUE THREAD

**Issue by abmai** [uber-web/baseui#237]
We want to be able to have full control over the `.value` of the `Input` component. Using `StatefulInput` means we don't have a way to programmatically clear the value when we need to. So we're trying to use `Input` directly, but right now we'd have to explicitly set `value={null}` when rendering the component to get a fully-uncontrolled `Input`, which seems a bit unintuitive imo.

To expand, we want this simple behavior to work by default:

```js
import React from 'react';
import {Input} from 'baseui/input';

export function MyComponent() {

  const inputRef = React.createRef();

  return (
    <div>
      <Input inputRef={inputRef} />
      <ClearButton
        onClick={() => {
          inputRef.current.value = '';
        }}
      />
    </div>
  );
}
```

Except `Input` here isn't registering user-input by default because internally it is setting `value = ''` as a default prop. We would need to render it like so in order to get it to behave like a normal HTML input

```js
<Input inputRef={inputRef} value={null} />
```

Was this intended as a default? If not, easy fix is to remove the default prop on `value` here. cc @nadiia  @schnerd

**Comment by schnerd** [comment]
I'm sort of confused on the use case. You can obtain "full control over the input" by passing a `value` prop to it. Why doesn't the following work?

```js
import React from 'react';
import {Input} from 'baseui/input';

export class MyComponent extends React.Component () {
  state = {inputValue: ''};
  return (
    <div>
      <Input 
         value={this.state.inputValue} 
         onChange={e => this.setState({inputValue: e.target.value})}
      />
      <ClearButton
        onClick={() => this.setState({inputValue: ''})}
      />
    </div>
  );
}
```

**Comment by abmai** [comment]
We're not keeping track of the `value` ourselves. In this case, we would like to just leave it to the DOM and react to it through the `onChange` handler.

From another perspective, I would expect this input to be functional, but it's not (it doesn't accept user input) until I explicitly set `value={null}`.

```js
import {Input} from 'baseui/input';

// Does not accept user input
const MyComponent = () => (
  <Input />
)

// Now it accept user input
const MyComponent = () => (
  <Input value={null} />
)
```

**Comment by schnerd** [comment]
Interesting – you're right that this is how native `input` behaves in React. Though I do wonder if they were forced to support both behaviors in a single native element, whereas in userland we have the ability to define StatefulInput and Input.

It does still feel a bit strange – like you're trying to use a stateless component as a stateful component. But that said, if the only thing we need to change to support this is to remove the defaultProp for value, then that seems like a fine change to me. 

Just curious, what are you doing with the value in `onChange`? I'd assume you're either storing it in redux or component state. And if so, why not just feed it back into the `value` prop to avoid all the ref nonsense?

**Comment by abmai** [comment]
> Just curious, what are you doing with the value in onChange? I'd assume you're either storing it in redux or component state. And if so, why not just feed it back into the value prop to avoid all the ref nonsense?

Haha, that's certainly a design choice that needs to be re-visited. We will probably refactor to do that at some point (seems like controlled form component is what React recommends anyway), but are trying to do the least amount of work to integrate Base UI atm and ran into this peculiarity.

And yes, the only change here is to remove the default prop for `value`, wanted to make sure it wasn't something we intended to do originally first. I can throw up a quick PR.

**Comment by nadiia** [comment]
I would agree with the David's comment on this interesting approach, but setting it to `null` seems reasonable. Thanks for the PR for it!
