### ISSUE TITLE
[Theming] create a theme factory?

### ISSUE THREAD

**Issue by jckr** [uber-web/baseui#252]
* [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
TL;DR - I want to be able to create variations of existing themes. Right now in the LightTheme, a lot of the options come from constants in the file which are not exposed. What if in addition to existing themes we added a function that could take parameters (such as fonts, colors etc.) and generated a new theme? 
For instance: 
```
import {LightTheme, createTheme, ThemeProvider} from 'baseui';
const myTheme = createTheme({template: LightTheme, primaryFontFamily: 'Times New Roman'});
const myComponent = <ThemeProvider theme={myTheme}>
... 
</ThemeProvider>
```
## Current Behavior
If I want to create a full theme I can either create it from scratch or at the very least override all the items I need to change even if they contain similar information. 

## Context
I'd like to set my typography choices once and for all and probably not use Helvetica.

**Comment by schnerd** [comment]
There are some related ideas in #48

**Comment by jckr** [comment]
also I just worded the issue. The idea came from @schnerd as an answer to how this could be done. 
So I'm new to this. What's the approach for creating proofs of concept?

**Comment by abmai** [comment]
Similar ideas indeed. Do we want to first proceed with a short RFC on how the theme creation/extension could be improved? @jckr I don't think we have a particular RFC format for non-component RFC so it's pretty much free-form at this point.

**Comment by schnerd** [comment]
I think this exists now, see docs here:
https://github.com/uber-web/baseui/tree/master/src/themes

Feel free to re-open if there's still functionality that's missing.
