### ISSUE TITLE
Fail to build in udeploy after adding baseui into package.json

### ISSUE THREAD

**Issue by ywu151** [uber-web/baseui#270]
* [ ] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Project could build in udeploy after adding baseUI

## Current Behavior
It always fails in building in udeploy  after adding baseUI

## Context
I use `yarn add baseui` to my project. It works well locally. While it always fails in building in udeploy.
My master branch builds successfully. And I push a branch only add baseUI to package and its yarn.lock. It fails building.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v1.?.?  |
| React   |         |
| browser |         |
| node.js |         |
| etc.    |         |

## Steps to Reproduce

Link:

1.

**Comment by abmai** [comment]
@ywu151 `baseui` needs `styletron-standard` and `styletron-react-core` as `peerDependencies` - so I think you need to install those in your app separately. Can you double check that you have these peerDependencies installed?

https://github.com/uber-web/baseui/blob/master/package.json#L106

**Comment by nadiia** [comment]
What version of baseui was installed? @ywu151 could you update the package to the latest?

**Comment by gergelyke** [comment]
closing in favor of discussing internally.

**Comment by ywu151** [comment]
Resolved by adding/updating either the peer deps or an unrelated dep
[https://code.uberinternal.com/rMAIROIO8e3cb437c069076f655870133112efc33cbf5446](https://code.uberinternal.com/rMAIROIO8e3cb437c069076f655870133112efc33cbf5446) and [https://code.uberinternal.com/rMAIROIO2e4fd681d818d666965df8e3e94dcc4edde08cda](https://code.uberinternal.com/rMAIROIO2e4fd681d818d666965df8e3e94dcc4edde08cda)
Thx to help from @abmai
