### ISSUE TITLE
Menu Component: Use margin instead of padding for first/last child options

### ISSUE THREAD

**Issue by schnerd** [uber-web/baseui#298]
Current hover style:
![kapture 2018-09-24 at 10 37 52](https://user-images.githubusercontent.com/875591/45968564-322d1a00-bfe6-11e8-95a5-ab2ba147f787.gif)

Desired hover style:
![kapture 2018-09-24 at 10 39 11](https://user-images.githubusercontent.com/875591/45968569-36f1ce00-bfe6-11e8-8d17-adc7abba058b.gif)

@nguyensomniac thoughts?

**Comment by schnerd** [comment]
Actually Lily is out of office but just checked with Jeff and the second one is the intended style.

**Comment by abmai** [comment]
Built the first one with intention, probably should have checked with design first. I'll put up a fix!
