### ISSUE TITLE
[Select] Overrides Style for Select Should Have A Simple Way

### ISSUE THREAD

**Issue by ywu151** [uber-web/baseui#308]
* [ ] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Overrides style could be passed easily, for example:
```
<StatefulSelect
  overrides={{
    Root: {style: {width: '280px'}}
  }}
>
``` 

## Current Behavior
We have to import`StyledRoot` and redefine it in order to change the styles.
```
            <StatefulSelect
              overrides={{
                Root: props => (
                  <StyledRoot {...props} style={{width: '280px'}} />
                ),
              }}
              options={options}
              initialState={{selectedOptions}}
              onChange={(e, {label: type}) => {
                this.setState({type});
              }}
              rows={7}
            />
```

## Context
The width of select component will change based on content which are not suitable in some cases, for example:
![single-select](https://user-images.githubusercontent.com/33992458/46042210-b2787b80-c0c9-11e8-9516-38ed96bbff5a.gif)

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v1.11.0  |
| React   |         |
| browser |         |
| node.js |         |
| etc.    |         |

## Steps to Reproduce

Link:

1.

2.

3.

4.

**Comment by nadiia** [comment]
@ywu151 Could you update to the latest version and verify if you still see any of the above issues?

**Comment by ywu151** [comment]
No, it works well new. Thx for your work
