### ISSUE TITLE
Add more icons

### ISSUE THREAD

**Issue by shanshanzhu** [uber-web/baseui#388]
Add icons such as chevron-up and chevron-right, alert with exclamation point in a triangle 

* [x ] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

There should be more Icons than it currently has.

## Current Behavior

Limited choices of icons

**Comment by gergelyke** [comment]
Hi @shanshanzhu ! for a more comprehensive list of icons, please use the internal `@uber/icons` package.
