### ISSUE TITLE
Modal Background Scroll Bar Lock

### ISSUE THREAD

**Issue by hanweifish** [uber-web/baseui#414]
Want to have scroll bar lock when modal open,
but tried with Root overflow none does not work.

What dost "Root" point to and how to lock the background if possible? 

Ref: overrides: {Root, Backdrop, Dialog, DialogContainer, Close}

**Comment by schnerd** [comment]
Thanks for opening this issue – preventing background scroll when a modal is open is definitely something we should support.

The `Root` element is just the element holding the modal overlay and its contents, applying `overflow: hidden` to that element won't necessarily prevent the background from scrolling.

Most modal implementations apply `overflow: hidden` to the body element when the modal is open.  [Material-ui](https://material-ui.com/demos/dialogs/), [rc-dialog](https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L332) are good examples. We should probably do the same in baseui.

As a short-term fix you may be able to toggle this body style manually when opening/closing the modal. We'll work on fixing this natively in baseui (contributions are welcome).
