### ISSUE TITLE
Declarative API for Toast components

### ISSUE THREAD

**Issue by KevinGrandon** [uber-web/baseui#446]
### Problem
The current API of the Toast component makes it difficult to render on the server. This means applications which leverage Fusion.js, or SSR, will have a difficult time working with the Toast component.

This has further implications in a redux world when I would expect to be able to use an API like:
```js
  {this.state.errorFromRedux && <Toast ... />}
```

### Recommendation:
Allow for SSR of the Toast component, showing on first load, and disappearing once JS has loaded. I would also recommend removing the programmatic API, and sticking with idiomatic React and JSX if possible.

Consider looking at the material-ui snackbar implementation: https://material-ui.com/demos/snackbars/

**Comment by gergelyke** [comment]
Thanks Kevin! We've added it to our backlog & will tackle this in the next couple sprints!
