### ISSUE TITLE
Suggested syntax for inlined override components in documentation is flawed

### ISSUE THREAD

**Issue by phou87** [uber-web/baseui#457]
The documentation suggests providing overrides in the following manner:
```
<Checkbox
  overrides={{Root: props => <Foo {...props />}}
/>
```

However, this leads to problems with several of the BaseUI components. Below is an example:

https://codesandbox.io/s/6wz97z4qn3

Try checking/unchecking the box and then de-focusing it by clicking the text input. Notice that the styling stays focused.

The reason this doesn't work is that the arrow function creates a new component on each render. This gets passed down to Checkbox. Checkbox itself stays mounted, but the Root (and as a result, its children) get unmounted and remounted since React thinks it's a different component. Because Checkbox stays mounted, it retains its focus state.

When the checkbox is clicked, its focus/change handlers fire. The focus state of Checkbox is set to true. The parent responds to onChange by re-rendering. The underlying Root (and `<input>`) get recreated. Now the underlying input is not focused! Thus, its blur event will not trigger when clicking away. Re-clicking the checkbox does not help because the destruction/construction cycle happens again.

Suggestion: update the documentation to create override components outside of render. The above example is even simpler and can be replaced by:

```
<Checkbox
  overrides={{Root: Foo}}
/>
```

**Comment by schnerd** [comment]
Great find. Makes sense – defining override functions inline implicitly creates a new component on each render. Sounds like a good pitfall to call out in general overrides documentation, and we should audit overrides examples for all existing components.

**Comment by gergelyke** [comment]
Hi @phou87 , @schnerd,

thanks for bringing it up! We've just created a story for our next sprint and we'll tackle it then!

**Comment by gergelyke** [comment]
@phou87 @schnerd can you take a look https://github.com/uber-web/baseui/pull/491 ?
