### ISSUE TITLE
[Theming] `borders.useRoundedCorners` prop check along with border radius values

### ISSUE THREAD

**Issue by nadiia** [uber-web/baseui#48]
Seems like the usage of `borders.useRoundedCorners` alongside of `borders.radiusX` can introduce some confusion around the combination of two. When all `borders.radiusX` values are set to `0` while `borders.useRoundedCorners` is still set to `true`. Or what would be the situations one would not use the `useRoundedCorners` check in the border-radius declaration. 

Let's rethink the need of this additional `useRoundedCorners` check. @schnerd

**Comment by gergelyke** [comment]
@schnerd  @nadiia is this still something we want to work on? or should we close it?
