### ISSUE TITLE
[DISCUSSION] Modify theming scale values to allow style calculation

### ISSUE THREAD

**Issue by austin94** [uber-web/baseui#512]
* [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

While developing or overriding components that consume theme values I expect to be able to calculate associated styling values from the theme provided.

i.e. If a style in a component should always have a `marginTop` value that is 50% the height of the current font `lineHeight`, I should be able to apply the size via

```
{
    marginTop: `${$theme.typography.font200.lineHeight / 2}px`
}
```

This would allow a theme to modify the typography without breaking the spacing provided within a component.

## Current Behavior

All spacing, border, and sizing values are represented as `string`s. This makes ratio calculations impossible.  

I suggest we convert these values to `number`s (BREAKING change).

## Context

I ran into some customization issues between the typography provided by the `default` and `UberMove` theme while implementing the `ProgressSteps` component.

**Comment by schnerd** [comment]
It's maybe worth pointing out that such a change would make baseui a strict pixel-based system. As of right now customers could theoretically create a theme that uses `rem`/`em` for font sizes or spacing. Not necessarily a blocker, but worth considering.

One alternative to consider, though I'm not 100% sure of the support/performance implications, is using `calc()`, which works with any units

```js
{
    marginTop: `calc(${$theme.typography.font200.lineHeight} / 2)`
}
```

I'd be curious to hear design's take on this as well. When building these are they thinking in terms of "half of line height", or are they relying on the `scale` system to ensure consistent spacing?

cc @nguyensomniac

**Comment by nguyensomniac** [comment]
> I'd be curious to hear design's take on this as well. When building these are they thinking in terms of "half of line height", or are they relying on the scale system to ensure consistent spacing?

The latter! We lean on the `scale` system—it's a bit manual in that sense but helps us enforce a 4px grid system everywhere.

**Comment by leyanlo** [comment]
+1 for @schnerd's comment about using `calc()`. Much prefer having scale values you can use directly without having to concatenating units everywhere to use them

**Comment by austin94** [comment]
`calc()` is supported all the way down to IE10 so we should be good for browser compatibility.  

If there isn't a need for non-CSS logic around the theming values I think that would be the preferred path.

**Comment by blackswanny** [comment]
So I vote for this improvement as I believe in responsive design, which is easier to develop with relative units (`em`, `%` or `rem`). We can apply pixels as default units as middleware between styletron and base ui. However, adding `px` or other units (overriden) adds some extra performance here

**Comment by leyanlo** [comment]
I'm not sure if this would actually help in terms of responsive design, though. If, for example, we were to set `typography.font200.lineHeight` to `20` instead of `'20px'`, how else would we use it? Unless I'm missing something, there probably isn't a case where we would want `20em` or `20%` or `20rem` from this. Really it only makes sense as a pixel value, and therefore it's actually helpful that we label it as such.

**Comment by austin94** [comment]
I agree with @leyanlo. I'm going to close this in favor of using `calc()`

**Comment by blackswanny** [comment]
@leyanlo So with relative `em`, `rem` and `%` we can change base font size 
(usually applied to `body`) or other size to force the whole app be scaled correspondingly.

**Comment by audiocommander** [comment]
hm, just stumbled upon this really nice project, but I wonder why there are still so many pixel-values all over the place (e.g. [sizing](https://baseweb.design/theming/theming-values/))? Using px values is an absolute no-go for me, as making things responsive and inclusive/barrier-free is a top priority. Is there any roadmap to get rid of px values?

I'm using `em` and `rem` with priority, `%` and in case I need absolute values `vh` and `vw`.
I'm not using any library or framework that introduces absolute `px`-values, as this introduces only problems.

Sorry for re-opening, but I think this thread is a good fit for my question.

**Comment by tonypee** [comment]
Im very interested in @audiocommander 's question. As we are assessing the library, but need to use rem's. Is it just a matter of restyling the units to rem units?

**Comment by sandgraham** [comment]
@tonypee - You can set the `sizing` scale to be any unit and things should adjust accordingly. This is because we don't make assumptions about the units you assign to the scale when using them in styling code.

```
// yes
marginLeft: theme.sizing.scale400

// no
marginLeft: `${theme.sizing.scale400}px`
```

There are `px` units used in certain circumstances though- mostly border widths and certain elements that need to be absolutely sized (or at least for our purposes are always an exact size in px). I think in these cases a simple styling override is probably sufficient.

All that said, we are comfortable with `px` values in our own apps and don't test the components with relative units.

**Comment by tonypee** [comment]
thanks for the reply

**Comment by RobIsHere** [comment]
Thank you  @sandgraham. That was the missing piece of information. 

For completeness: 
Add units automatically in styletron https://github.com/styletron/styletron/issues/35

**Comment by RobIsHere** [comment]
After trying this, the only blocker is the type configuration of the theme. 
Could we change string types into string | number for sizes, length, widths etc ?
