### ISSUE TITLE
Toast icon is slightly uncentered

### ISSUE THREAD

**Issue by shanshanzhu** [uber-web/baseui#526]
* [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior
Adding some margin to the close icon

Close Icon should be centered.
For example, adding a {marginTop: '2px'} to the svg fix it.
## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v4.4.1 |
| React   |         |
| browser |         |
| node.js |         |
| etc.    |         |

## Steps to Reproduce

Link:
https://baseui.netlify.com/?selectedKind=Toast&selectedStory=Toast%20notifications&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

Close icon is moved to the top slightly.

**Comment by gergelyke** [comment]
Hi @shanshanzhu ! Thanks for opening this issue!

The toast component follows our design spec, and the close icon is not meant to be centered:

<img width="513" alt="screen shot 2018-11-20 at 11 12 25 am" src="https://user-images.githubusercontent.com/2174968/48796739-41160d00-ecb5-11e8-84cb-47a896094a49.png">

**Comment by shanshanzhu** [comment]
The top of close icon is not aligned with the top of the text like the previous version. We notice this change when upgrading from v2.3.0 to v4.4.x.

It looks odd when the text is only one line

**Comment by shanshanzhu** [comment]
Latest 4.4.x version
![screen shot 2018-11-20 at 12 05 13 pm](https://user-images.githubusercontent.com/5092813/48799655-9bff3280-ecbc-11e8-9ff5-3b4750337bbd.png)

2.3.0 version
![screen shot 2018-11-20 at 12 01 50 pm](https://user-images.githubusercontent.com/5092813/48799656-9bff3280-ecbc-11e8-8fab-1c1badde4c50.png)
