### ISSUE TITLE
Component props should use exact types

### ISSUE THREAD

**Issue by vicapow** [uber-web/baseui#529]
This will help prevent regressions for deprecated/renamed props, like `rows` which was renamed `maxDropdownHeight`.

**Comment by chasestarr** [comment]
Our plan is to publish new components with exact prop types, but maintain the current inexact prop types until flow updates to exact by default. See [this comment](https://github.com/uber-web/baseui/pull/1525#issuecomment-511540957) for more thoughts. Going to close this for now. We've heard the feedback and will keep this in mind when making changes
