### ISSUE TITLE
shadowFocus and shadowError colors

### ISSUE THREAD

**Issue by agentcooper** [uber-web/baseui#537]
In https://github.com/uber-web/baseui/blob/master/src/themes/creator.js#L121:
```js
shadowFocus: 'rgba(39, 110, 241, 0.32)',
shadowError: 'rgba(229, 73, 55, 0.32)',
```

Shouldn't those be calculated from `primary400` and `negative400` accordingly?

I did a quick fix for my theme with

```js
FancyTheme.colors.shadowFocus = calcShadow(FancyTheme.colors.primary400);

function calcShadow(hex) {
  const rgb = hexToRgb(hex);
  return `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, 0.32)`;
}

// from https://stackoverflow.com/questions/5623838/rgb-to-hex-and-hex-to-rgb
function hexToRgb(hex) {
  var result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result
    ? {
        r: parseInt(result[1], 16),
        g: parseInt(result[2], 16),
        b: parseInt(result[3], 16),
      }
    : null;
}
```

If this looks sane, I can open a PR.

**Comment by austin94** [comment]
These values should definitely be calculated form the theme variables.

This conversion could be easy enough for us to maintain the transform utilities are selves, but I could see us needing some more advanced operations in the future. 

Could this be a good time to leverage https://polished.js.org/ ?  Should be a very limited bundle increase and has some more advanced utilities like `parseToRgb` and `transparentize(FancyTheme.colors.primary400)`

**Comment by jh3y** [comment]
After some discussion, we agreed to close this issue. The theme primitives are static. The desire for shadows that match the theme colors is subjective. A utility function is also currently out of scope for `baseui` and would be something to additionally maintain.
