### ISSUE TITLE
flow $Values utility type does not match against literal

### ISSUE THREAD

**Issue by chasestarr** [uber-web/baseui#539]
originally brought up by @brentertz in baseui [slack](https://baseui.slack.com/archives/CCGJPJA1H/p1543243130000200)

## Current Behavior

```js
const FOO = {
  bar: 'bar',
  bas: 'bas'
};

type Foo = $Values<typeof FOO>
  
// Works
const v1: Foo = 'bar';

// Errors
const v2: Foo = 1;

// Does not error, but should
const v3: Foo = 'quux';
```

## Context

Flow's `$Values` utility type by default does not compare against the string literal, but instead compares to simple string type. The referenced object should be frozen to operate as expected.

```js
const FOO = Object.freeze({
  bar: 'bar',
  bas: 'bas'
});

type Foo = $Values<typeof FOO>
  
// Works
const v1: Foo = 'bar';

// Errors
const v2: Foo = 'quux';
```

5 or so [instances](https://github.com/uber-web/baseui/search?utf8=%E2%9C%93&q=%24values%3C&type=) of this in the code base

**Comment by gergelyke** [comment]
Thanks for opening this Chase! Adding it to our backlog
