### ISSUE TITLE
[Tag] Tag component doesn't handle text overflow when the width of a tag is limited

### ISSUE THREAD

**Issue by nadiia** [uber-web/baseui#572]
* [ x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

<img width="202" alt="screen shot 2018-11-30 at 1 18 52 am" src="https://user-images.githubusercontent.com/1920399/49280414-fe83cb80-f43e-11e8-8f3b-1e2b1ea65b29.png">
or
<img width="212" alt="screen shot 2018-11-30 at 1 26 10 am" src="https://user-images.githubusercontent.com/1920399/49280419-017ebc00-f43f-11e8-93a4-25ab7d503cf0.png">

## Current Behavior

<img width="206" alt="screen shot 2018-11-30 at 1 18 14 am" src="https://user-images.githubusercontent.com/1920399/49280445-15c2b900-f43f-11e8-885f-ad4260cef91e.png">

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v5.1.0  |

**Comment by chasestarr** [comment]
fixed here: https://github.com/uber-web/baseui/pull/882
