### ISSUE TITLE
Return `mixed` type instead of `void`

### ISSUE THREAD

**Issue by NameFILIP** [uber-web/baseui#626]
It's better to specify a `mixed` return type instead of `void` on the component handlers like:

```
onClick?: (SyntheticEvent<HTMLButtonElement>) => void,
```

[.../button/types.js](https://github.com/uber-web/baseui/blob/master/src/button/types.js#L29).

`mixed` means the function can return anything and do not care what it is unless you need to use it.

**Comment by schnerd** [comment]
+1 for being more flexible with the return types. One case where I've found this useful is if I want to make my handler an async function.

```
async onChange (params) {
  await fetch('/api', params);
}
```

^ async functions implicitly return a promise and flow complained that baseui expected void. Seems like `mixed` would fix this–I don't have a better alternative.

**Comment by chasestarr** [comment]
good suggestion. I think making this change should be safe

**Comment by tseth-uber** [comment]
I think this should be done. I'm bumping into the issue now.

**Comment by gergelyke** [comment]
this is released
