### ISSUE TITLE
[Select] Clicking on the select control or the select arrow should toggle the dropdown

### ISSUE THREAD

**Issue by nadiia** [uber-web/baseui#649]
* [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

Clicking on the select control or the select arrow while the dropdown is open should close the drop-down. A subsequebt click should toggle the drop-down.

## Current Behavior

Clicking on the select control or the select arrow while the drop-down is open re-opens the drop-down.

**Comment by gergelyke** [comment]
can we close this @tajo ?
