### ISSUE TITLE
[Select] Make the first item be selectable by default on type+hit Enter action

### ISSUE THREAD

**Issue by nadiia** [uber-web/baseui#671]
* [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

## Expected Behavior

When start typing set the highlighted index in the dropdown to the first item and make it selectable on when Enter is pressed.

## Current Behavior

While typing and having the dropdown opened with list of items hitting Enter doesn't do anything unless you arrowDown into the dropdown first

![sel3](https://user-images.githubusercontent.com/1920399/50190606-be499780-02de-11e9-8a63-179e990eb1c5.gif)

**Comment by gergelyke** [comment]
can we close this @tajo ?
