### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by chasestarr** [uber-web/baseui#672]
chose to base support off of `css-grid` https://caniuse.com/#feat=css-grid

browsers in the table linked [here](https://caniuse.com/#compare=ie+11,edge+16,firefox+60,chrome+58,safari+10.1,opera+44,ios_saf+10.3,android+67,and_chr+70&compare_cats=CSS,HTML5,JS,JS%20API,Other,SVG) are what i recommend

IE 11
Edge 16
Firefox 60 ([esr](https://www.mozilla.org/en-US/firefox/organizations/))
Safari 10.1
Opera 44
iOS Safari 10.3
Android os v4.4
chrome 58

**Comment by gergelyke** [comment]
do you want to open a PR to add it to the docs site?

**Comment by chasestarr** [comment]
yes, I will after reviewing browser usage in GA
