### ISSUE TITLE
Intro pages in Storybook stopped working

### ISSUE THREAD

**Issue by schnerd** [uber-web/baseui#696]
https://baseui.design/?selectedKind=Theming&selectedStory=Theming%20values&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

![image](https://user-images.githubusercontent.com/875591/50526499-5130c180-0a97-11e9-953b-29c6959c2a3d.png)

Looks like Introduction, Contributing, and Theming pages stopped working in Storybook. I'm assuming they got left behind in the recent shuffling of component README files.

**Comment by gergelyke** [comment]
They are there, but for some reason it shows you the bottom content only in full screen - you can drag this little thing to show the content:

<img width="800" alt="screen shot 2018-12-28 at 2 04 02 pm" src="https://user-images.githubusercontent.com/2174968/50529449-bc838f00-0aa9-11e9-97af-9a246e748996.png">

**Comment by gergelyke** [comment]
Please reopen if it does not work for you

**Comment by schnerd** [comment]
Weird – I think this happened when switching between an external monitor and laptop screen with different sizes. Thanks for looking into it.
