### ISSUE TITLE
[Select]  Allow component to mount with dropdown rendered

### ISSUE THREAD

**Issue by yogurtandjam** [uber-web/baseui#744]
## Feature description

Either by altering the implementation of autoFocus or by adding a new prop, allow the user to pass in a prop to Select/StatefulSelect that allows it to render the dropdown upon mounting.

Currently, autoFocus does focus the component when it mounts, but it does not trigger a dropdown render. Feel free to play with this code sandbox https://codesandbox.io/s/8k682q3nrl

**Comment by IgorWilbert** [comment]
Hey! Is this issue still available. If yes, may I take it? Thanks!
