### ISSUE TITLE
[Datepicker] Interaction leads to page scroll

### ISSUE THREAD

**Issue by agentcooper** [uber-web/baseui#813]
Clicking on the year scroll the page up. Probably an anchor issue.

1. Open https://baseui.design/components/datepicker/
2. Scroll the page a bit
3. Click on the year in the Datepicker

## Current Behavior

Page scrolls up.

## Expected Behavior

Scroll should not be affected.

## Your Environment

BaseUI on https://baseui.design/components/datepicker/.

**Comment by gergelyke** [comment]
fixed
