### ISSUE TITLE
[checkbox] allow stylings/ 'compact' prop

### ISSUE THREAD

**Issue by yogurtandjam** [uber-web/baseui#849]
Some components allow for a compact/smaller version. This can be handled with an override but it would be great if the users of the StatefulCheckbox component had some power over some of the stylings.

Or if nothing else, allowing for a compact version as is available in some other baseUI components would be awesome!

As you can see, the current layout I have looks less than optimal.

Worst comes to worst I can always use an override, but thought this might be a relatively simple change on your end that might make this component a bit more reusable!

<img width="521" alt="screen shot 2019-02-04 at 5 44 30 pm" src="https://user-images.githubusercontent.com/37092291/52248710-87d2d680-28a4-11e9-8b94-a29360601191.png">

**Comment by gergelyke** [comment]
Hi @yogurtandjam, thanks for raising this! We'll work with design to land this soon in Base UI
