### ISSUE TITLE
[block] Adding more props, e.g. backgroundColor

### ISSUE THREAD

**Issue by kahwee** [uber-web/baseui#859]
These are fairly common use cases for a couple of projects I'm working on.

Can we have the following props available for Block?

* `backgroundColor?: string`
  * Accepts all themeable color properties (`primary200`, etc.).
* `lineHeight?`: [available values](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height)
* `fontWeight?`: [available values](https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight)
* `marginX?: string`
  * Accepts all themeable sizing properties (`scale100`, etc.).
* `marginY?: string`
  * Accepts all themeable sizing properties (`scale100`, etc.).
* `paddingX?: string`
  * Accepts all themeable sizing properties (`scale100`, etc.).
* `paddingY?: string`
  * Accepts all themeable sizing properties (`scale100`, etc.).

Where `X` is the `Left` and `Right` of `margin` / `padding`

Where `Y` is the `Top` and `Bottom` of `margin` / `padding`

**Comment by jh3y** [comment]
Hey @kahwee 👋 

Not sure if this would be an accepted solution. To apply certain styles to a `Block`, you could do this via the `overrides` prop.

```js
<Block
  overrides={{
    Block: {
      style: ({ $theme }) => ({
        backgroundColor: $theme.colors.primary200,
    }),
  },
}}>
```

**Comment by leyanlo** [comment]
I think `backgroundColor` makes sense, but shouldn’t `lineHeight` and `fontWeight` come from one of your `font` theme values? Also the X and Y versions of margin/padding seem a little non-standard, not part of CSS or Styletron. Are the `margin` and `padding` shorthands not enough for this purpose?
