### ISSUE TITLE
Allow date picker quick select to be used for single-day selects

### ISSUE THREAD

**Issue by bencohen2** [uber-web/baseui#883]
## Feature description
Quick select on date pickers is only enabled for date pickers for which `isRange` is `true`. Would be great to allow quick select for date pickers where the goal is to pick one specific date.

**Comment by chasestarr** [comment]
can you provide some examples of useful quick select options?

**Comment by bencohen2** [comment]
A user is scheduling an appointment for a specific day/time, and 'today' or 'tomorrow' could be quick select links for that specific day
