### ISSUE TITLE
BaseUI Block `gridTemplateColumns` accepts array of values but throws Flow error

### ISSUE THREAD

**Issue by bschwartz757** [uber-web/baseui#918]
## Current Behavior

I am able to pass an array of values to a BaseUI `Block` component and those values are used as media queries - they behave as one would expect, and I don't see any errors/warnings in my editor (VSCode). However, when I run `yarn flow` on my project, it throws an error: 

```
            <Block
              as="div"
              display="grid"
              gridGap="1rem"
              gridTemplateColumns={[
                'repeat(auto-fill, minmax(400px, 1fr))',
                'repeat(auto-fill, minmax(200px, 1fr))',
                'repeat(auto-fill, minmax(400px, 1fr))',
                'repeat(auto-fill, minmax(400px, 1fr))',
                'repeat(auto-fill, minmax(600px, 1fr))',
              ]}
              gridAutoRows="minmax(200px, auto)"
            >
```
...
`Cannot create Block element because array literal [1] is incompatible with string [2] in property gridTemplateColumns.`

## Expected Behavior

According to the BaseUI docs for `Block`:

>Block component props accept either a single value or array of values. When an array is provided, it will create media queries for each item based on the theme breakpoint values. 

I would expect that this should not cause a Flow error.
## Your Environment

| Fusion.js    | Core version: 1.10.1 |
| Flow    | Version: 0.89.0 |
| ------- | ------- |
| Base UI | v6.0.1  |
| React   |     16.7.0    |
| browser |   N/A      |

- [ ] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by gergelyke** [comment]
Fixed
