### ISSUE TITLE
Accordion's Stateful panel does not respond to "expanded" props

### ISSUE THREAD

**Issue by zebralight** [uber-web/baseui#945]
## Current Behavior
When passing in a value for expandable like so `<StatefulPanel expanded={true} >...`, the component does not render expanded per the documentation.

## Expected Behavior
From API docs: 
```
expanded boolean
Defines if the panel is expanded. If set to true the panel is rendered expanded.
```

See "Expected Behavior"
## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v6.2.0  |
| React   |         |
| browser |         |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

**Comment by chasestarr** [comment]
responded in the pr
