### ISSUE TITLE
[Menu/Select] make hovered item equivalent to highlighted item

### ISSUE THREAD

**Issue by chrisirhc** [uber-web/baseui#993]
## Feature description
I think it could be useful to unify the hover and keyboard interactions so that the user can highlight a menu item, and use up/down keys to move the selection up and down.

This avoids the following inconsistent states (Case 1, 2):

Case 1: there's a highlighted selection and also a hovered selection (via the mouse):
<img src="https://user-images.githubusercontent.com/132584/53932592-2e022f80-404f-11e9-834e-dd5639861ba7.png" width="300">

Case 2: there's a highlighted option and a child menu of a menu that's not highlighted:
![image](https://user-images.githubusercontent.com/132584/53932647-74f02500-404f-11e9-88f3-600ec54e330e.png)

I'm not sure if this was by-design, but I think it might be worth revisiting the design if it is.

## Use case
I wanted to show additional information based on the highlighted item in the menu, a custom hover popover on the highlighted item.

## Proposed solution
A first step in resolving this is to only keep a highlighted state. However in multi-level menus, it's hard to tell where is the cursor/selection without an actual cursor, we'll need to disambiguate what is the focus item since the following is no longer satisfies [focus visible accessibility concerns](https://w3c.github.io/wcag/guidelines/#focus-visible). Hence, we do need to bring back that the state where the "blue" indicates the focus.

Counter-example with 2 highlighted values (does not show focus): 
![image](https://user-images.githubusercontent.com/132584/53932828-82f27580-4050-11e9-8108-0dcd5a125348.png)

Final proposed solution:
![image](https://user-images.githubusercontent.com/132584/53933035-6c005300-4051-11e9-969f-070493efd359.png)

Each single menu should only have at most 1 blue highlighted item, which indicates the focus.

**Comment by gergelyke** [comment]
Thanks for raising this Chris! We have a task for this in our current sprint :) Let me link this issue to that story

**Comment by chasestarr** [comment]
Hi Chris - check out this [preview](https://deploy-preview-1016--baseui.netlify.com/components/menu/#menu-with-child-menu) of the proposed changes. Let me know if you have any feedback

**Comment by chrisirhc** [comment]
This looks great! A couple of things in my quick test.

Really liking:
* Outline indicating focus around the child menu! Nice touch.

Some things I noticed:
* When I clicked on an item in the Menu Stateful example, it seems that I'm unable to use the arrow keys (might unnecessary use case in real environments since the menu would close when something is selected, but it seemed odd when I tried it on the example page). This also sometimes happen when I hover over the Menu with Child Menu and move my mouse away, then try to use arrow keys.
* When I used the right arrow to go into a child item, it could get into a state where the submenu was focused but no item was selected. Up and down arrow would fix it. This seems like a weird state. 
![image](https://user-images.githubusercontent.com/132584/54457121-d6825480-471d-11e9-813d-2f7e658e247e.png)
* Arrow keys don't seem to work on the Menu with Long Items List

**Comment by gergelyke** [comment]
@chrisirhc any chance you had the time to take a look at the updated menu component? do you think we can close this issue, or are there open concerns?

**Comment by chrisirhc** [comment]
> @chrisirhc any chance you had the time to take a look at the updated menu component? do you think we can close this issue, or are there open concerns?

Please see my response above. I've reviewed the updated menu component and given my feedback in https://github.com/uber-web/baseui/issues/993#issuecomment-473415299

**Comment by chasestarr** [comment]
PR linked above fixes disabled keyboard navigation after a mouse-out, fixes the virtualized menu example, and initially highlights the first option on focus in. Thanks for the feedback!

**Comment by chrisirhc** [comment]
Nice! Thanks folks!
