### ISSUE TITLE
[Menu/Select] add onHighlightedItemChanged handler

### ISSUE THREAD

**Issue by chrisirhc** [uber-web/baseui#994]
## Feature description
Add a way to listen to changes in the highlighted item in a menu or select. It is called when the highlighted item changes and it can be called with null if no option is highlighted.

## Use case
Display additional information based on the highlighted item in the menu in a separate view.

**Comment by chasestarr** [comment]
Does this achieve what you're looking for? https://codesandbox.io/s/zkwjqo30rp

**Comment by chrisirhc** [comment]
@chasestarr yep, I did look at using the `stateReducer`, but forgot to clarify here that I couldn't find a way to attach a `stateReducer` on the `StatefulMenu` for a `select` component.

**Comment by chasestarr** [comment]
Thanks for the clarification. Looking into Menu component more next week.

**Comment by IgorWilbert** [comment]
Hello @chasestarr ! Does this issue still needs to be solved? If yes, may I take it? Thanks!

**Comment by chasestarr** [comment]
Thanks @IgorWilbert ! It's available. Thanks for taking a look. Please reach out if you have any questions about the project or the approach
